2025-01-19T06:02:56.620Z [31merror[39m: Error loading command from /Users/joshreed/Code/SummarizerBot/src/commands/audio/RecordCommand.js: Cannot read properties of undefined (reading 'get'){"stack":"TypeError: Cannot read properties of undefined (reading 'get')\n    at new RecordCommand (file:///Users/joshreed/Code/SummarizerBot/src/commands/audio/RecordCommand.js:9:39)\n    at file:///Users/joshreed/Code/SummarizerBot/src/deploy-commands.js:35:20"}
2025-01-19T06:02:56.627Z [31merror[39m: Error loading command from /Users/joshreed/Code/SummarizerBot/src/commands/audio/SetChannelCommand.js: Cannot read properties of undefined (reading 'get'){"stack":"TypeError: Cannot read properties of undefined (reading 'get')\n    at new SetChannelCommand (file:///Users/joshreed/Code/SummarizerBot/src/commands/audio/SetChannelCommand.js:9:33)\n    at file:///Users/joshreed/Code/SummarizerBot/src/deploy-commands.js:35:20"}
2025-01-19T06:02:56.628Z [31merror[39m: Error loading command from /Users/joshreed/Code/SummarizerBot/src/commands/audio/SetKeyCommand.js: Cannot read properties of undefined (reading 'get'){"stack":"TypeError: Cannot read properties of undefined (reading 'get')\n    at new SetKeyCommand (file:///Users/joshreed/Code/SummarizerBot/src/commands/audio/SetKeyCommand.js:9:32)\n    at file:///Users/joshreed/Code/SummarizerBot/src/deploy-commands.js:35:20"}
2025-01-19T06:02:56.629Z [31merror[39m: Error loading command from /Users/joshreed/Code/SummarizerBot/src/commands/audio/SetTimeIntervalCommand.js: Cannot read properties of undefined (reading 'get'){"stack":"TypeError: Cannot read properties of undefined (reading 'get')\n    at new SetTimeIntervalCommand (file:///Users/joshreed/Code/SummarizerBot/src/commands/audio/SetTimeIntervalCommand.js:9:33)\n    at file:///Users/joshreed/Code/SummarizerBot/src/deploy-commands.js:35:20"}
2025-01-19T06:02:56.630Z [31merror[39m: Error loading command from /Users/joshreed/Code/SummarizerBot/src/commands/audio/StatusCommand.js: Cannot read properties of undefined (reading 'get'){"stack":"TypeError: Cannot read properties of undefined (reading 'get')\n    at new StatusCommand (file:///Users/joshreed/Code/SummarizerBot/src/commands/audio/StatusCommand.js:9:39)\n    at file:///Users/joshreed/Code/SummarizerBot/src/deploy-commands.js:35:20"}
2025-01-19T06:02:56.630Z [31merror[39m: Error loading command from /Users/joshreed/Code/SummarizerBot/src/commands/audio/StopCommand.js: Cannot read properties of undefined (reading 'get'){"stack":"TypeError: Cannot read properties of undefined (reading 'get')\n    at new StopCommand (file:///Users/joshreed/Code/SummarizerBot/src/commands/audio/StopCommand.js:9:39)\n    at file:///Users/joshreed/Code/SummarizerBot/src/deploy-commands.js:35:20"}
2025-01-19T06:04:17.056Z [31merror[39m: Error loading command from /Users/joshreed/Code/SummarizerBot/src/commands/audio/RecordCommand.js: Cannot read properties of undefined (reading 'get'){"stack":"TypeError: Cannot read properties of undefined (reading 'get')\n    at new RecordCommand (file:///Users/joshreed/Code/SummarizerBot/src/commands/audio/RecordCommand.js:9:39)\n    at file:///Users/joshreed/Code/SummarizerBot/src/deploy-commands.js:35:20"}
2025-01-19T06:04:17.058Z [31merror[39m: Error loading command from /Users/joshreed/Code/SummarizerBot/src/commands/audio/SetChannelCommand.js: Cannot read properties of undefined (reading 'get'){"stack":"TypeError: Cannot read properties of undefined (reading 'get')\n    at new SetChannelCommand (file:///Users/joshreed/Code/SummarizerBot/src/commands/audio/SetChannelCommand.js:9:33)\n    at file:///Users/joshreed/Code/SummarizerBot/src/deploy-commands.js:35:20"}
2025-01-19T06:04:17.059Z [31merror[39m: Error loading command from /Users/joshreed/Code/SummarizerBot/src/commands/audio/SetKeyCommand.js: Cannot read properties of undefined (reading 'get'){"stack":"TypeError: Cannot read properties of undefined (reading 'get')\n    at new SetKeyCommand (file:///Users/joshreed/Code/SummarizerBot/src/commands/audio/SetKeyCommand.js:9:32)\n    at file:///Users/joshreed/Code/SummarizerBot/src/deploy-commands.js:35:20"}
2025-01-19T06:04:17.059Z [31merror[39m: Error loading command from /Users/joshreed/Code/SummarizerBot/src/commands/audio/SetTimeIntervalCommand.js: Cannot read properties of undefined (reading 'get'){"stack":"TypeError: Cannot read properties of undefined (reading 'get')\n    at new SetTimeIntervalCommand (file:///Users/joshreed/Code/SummarizerBot/src/commands/audio/SetTimeIntervalCommand.js:9:33)\n    at file:///Users/joshreed/Code/SummarizerBot/src/deploy-commands.js:35:20"}
2025-01-19T06:04:17.060Z [31merror[39m: Error loading command from /Users/joshreed/Code/SummarizerBot/src/commands/audio/StatusCommand.js: Cannot read properties of undefined (reading 'get'){"stack":"TypeError: Cannot read properties of undefined (reading 'get')\n    at new StatusCommand (file:///Users/joshreed/Code/SummarizerBot/src/commands/audio/StatusCommand.js:9:39)\n    at file:///Users/joshreed/Code/SummarizerBot/src/deploy-commands.js:35:20"}
2025-01-19T06:04:17.060Z [31merror[39m: Error loading command from /Users/joshreed/Code/SummarizerBot/src/commands/audio/StopCommand.js: Cannot read properties of undefined (reading 'get'){"stack":"TypeError: Cannot read properties of undefined (reading 'get')\n    at new StopCommand (file:///Users/joshreed/Code/SummarizerBot/src/commands/audio/StopCommand.js:9:39)\n    at file:///Users/joshreed/Code/SummarizerBot/src/deploy-commands.js:35:20"}
2025-01-19T06:23:58.808Z [31merror[39m: Error getting time interval for guild 1315144523336122469: baseConfig is not defined{"stack":"ReferenceError: baseConfig is not defined\n    at ConfigurationService.getTimeInterval (file:///usr/src/app/src/services/ConfigurationService.js:230:56)\n    at VoiceRecorder.startRecording (file:///usr/src/app/src/VoiceRecorder.js:228:51)\n    at RecordCommand.execute (file:///usr/src/app/src/commands/audio/RecordCommand.js:31:38)\n    at CommandRegistry.handleCommand (file:///usr/src/app/src/commands/audio/CommandRegistry.js:61:25)\n    at Bot.handleInteraction (file:///usr/src/app/src/bot.js:76:40)\n    at Client.emit (node:events:517:28)\n    at InteractionCreateAction.handle (/usr/src/app/node_modules/.pnpm/discord.js@14.17.3/node_modules/discord.js/src/client/actions/InteractionCreate.js:97:12)\n    at module.exports [as INTERACTION_CREATE] (/usr/src/app/node_modules/.pnpm/discord.js@14.17.3/node_modules/discord.js/src/client/websocket/handlers/INTERACTION_CREATE.js:4:36)\n    at WebSocketManager.handlePacket (/usr/src/app/node_modules/.pnpm/discord.js@14.17.3/node_modules/discord.js/src/client/websocket/WebSocketManager.js:348:31)\n    at WebSocketManager.<anonymous> (/usr/src/app/node_modules/.pnpm/discord.js@14.17.3/node_modules/discord.js/src/client/websocket/WebSocketManager.js:232:12)"}
2025-01-19T06:28:25.224Z [31merror[39m: Error handling command: Cannot read properties of undefined (reading 'error'){"stack":"TypeError: Cannot read properties of undefined (reading 'error')\n    at CommandRegistry.handleCommand (file:///usr/src/app/src/commands/audio/CommandRegistry.js:76:25)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Bot.handleInteraction (file:///usr/src/app/src/bot.js:76:13)"}
2025-01-19T06:30:28.124Z [31merror[39m: [VoiceRecorder] Error processing recording: fsSync is not defined{"stack":"ReferenceError: fsSync is not defined\n    at AudioService.convertToMp3 (file:///usr/src/app/src/services/AudioService.js:108:34)\n    at async VoiceRecorder.processRotatedRecording (file:///usr/src/app/src/VoiceRecorder.js:99:29)"}
2025-01-19T06:30:28.127Z [31merror[39m: [VoiceRecorder] Error processing rotated recording: fsSync is not defined{"stack":"ReferenceError: fsSync is not defined\n    at AudioService.convertToMp3 (file:///usr/src/app/src/services/AudioService.js:108:34)\n    at async VoiceRecorder.processRotatedRecording (file:///usr/src/app/src/VoiceRecorder.js:99:29)"}
2025-01-19T06:32:01.999Z [31merror[39m: Error handling command: Cannot read properties of undefined (reading 'error'){"stack":"TypeError: Cannot read properties of undefined (reading 'error')\n    at CommandRegistry.handleCommand (file:///usr/src/app/src/commands/audio/CommandRegistry.js:76:25)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Bot.handleInteraction (file:///usr/src/app/src/bot.js:77:13)"}
2025-01-19T06:32:02.111Z [31merror[39m: Failed to send error response: Interaction has already been acknowledged.{"requestBody":{"files":[],"json":{"type":4,"data":{"content":"There was an error executing this command!","tts":false,"enforce_nonce":false,"flags":64}}},"rawError":{"message":"Interaction has already been acknowledged.","code":40060},"code":40060,"status":400,"method":"POST","url":"https://discord.com/api/v10/interactions/1330424511308238930/aW50ZXJhY3Rpb246MTMzMDQyNDUxMTMwODIzODkzMDpxdVlXTDZmbGxmVFRJUWVKUWtxRTk4SGVBUVdDcnJZeDRXZHZKVmdnODd6T25kaWg2NVhxVlVyNGo3MVZNTG00WUZ2TmZBc0syZnFVNDhLV25ZU3JoZkY0RHR1VHdSMDBKMzFTRTk2VjdHb3NsQnBEck9WMkJnYWt4eG9seXVteA/callback?with_response=false","stack":"DiscordAPIError[40060]: Interaction has already been acknowledged.\n    at handleErrors (/usr/src/app/node_modules/.pnpm/@discordjs+rest@2.4.2/node_modules/@discordjs/rest/dist/index.js:727:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async BurstHandler.runRequest (/usr/src/app/node_modules/.pnpm/@discordjs+rest@2.4.2/node_modules/@discordjs/rest/dist/index.js:831:23)\n    at async _REST.request (/usr/src/app/node_modules/.pnpm/@discordjs+rest@2.4.2/node_modules/@discordjs/rest/dist/index.js:1272:22)\n    at async ChatInputCommandInteraction.reply (/usr/src/app/node_modules/.pnpm/discord.js@14.17.3/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:194:22)\n    at async Bot.sendErrorResponse (file:///usr/src/app/src/bot.js:96:17)\n    at async Bot.handleInteraction (file:///usr/src/app/src/bot.js:80:13)"}
2025-01-19T06:37:33.394Z [31merror[39m: Error executing command record: Interaction has already been acknowledged.{"requestBody":{"files":[],"json":{"type":4,"data":{"content":"❌ Failed to start recording. Please try again.","tts":false,"enforce_nonce":false}}},"rawError":{"message":"Interaction has already been acknowledged.","code":40060},"code":40060,"status":400,"method":"POST","url":"https://discord.com/api/v10/interactions/1330425900877217894/aW50ZXJhY3Rpb246MTMzMDQyNTkwMDg3NzIxNzg5NDpCbGdURGY0OEZpdFlqTXVnQlBZS3VzQVgyUzBUbFd4QkcwemtrUW9CVEx3ek1rMUNkanFTWHlLaENNMkFBd2RGc0Y2VHQwNzF4Z0xTU25xOU9EMTVxNFRFWFdCR0Z4aDRWZ0FIOEgwd1ViQ1RZc1dUaXRobGtyMDR5cjhkNEdqbA/callback?with_response=false","stack":"DiscordAPIError[40060]: Interaction has already been acknowledged.\n    at handleErrors (/usr/src/app/node_modules/.pnpm/@discordjs+rest@2.4.2/node_modules/@discordjs/rest/dist/index.js:727:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async BurstHandler.runRequest (/usr/src/app/node_modules/.pnpm/@discordjs+rest@2.4.2/node_modules/@discordjs/rest/dist/index.js:831:23)\n    at async _REST.request (/usr/src/app/node_modules/.pnpm/@discordjs+rest@2.4.2/node_modules/@discordjs/rest/dist/index.js:1272:22)\n    at async ChatInputCommandInteraction.reply (/usr/src/app/node_modules/.pnpm/discord.js@14.17.3/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:194:22)\n    at async RecordCommand.execute (file:///usr/src/app/src/commands/audio/RecordCommand.js:54:17)\n    at async CommandRegistry.handleCommand (file:///usr/src/app/src/commands/audio/CommandRegistry.js:65:13)\n    at async Bot.handleInteraction (file:///usr/src/app/src/bot.js:77:13)"}
2025-01-19T06:37:33.396Z [31merror[39m: Error handling command: Interaction has already been acknowledged.{"requestBody":{"files":[],"json":{"type":4,"data":{"content":"❌ Failed to start recording. Please try again.","tts":false,"enforce_nonce":false}}},"rawError":{"message":"Interaction has already been acknowledged.","code":40060},"code":40060,"status":400,"method":"POST","url":"https://discord.com/api/v10/interactions/1330425900877217894/aW50ZXJhY3Rpb246MTMzMDQyNTkwMDg3NzIxNzg5NDpCbGdURGY0OEZpdFlqTXVnQlBZS3VzQVgyUzBUbFd4QkcwemtrUW9CVEx3ek1rMUNkanFTWHlLaENNMkFBd2RGc0Y2VHQwNzF4Z0xTU25xOU9EMTVxNFRFWFdCR0Z4aDRWZ0FIOEgwd1ViQ1RZc1dUaXRobGtyMDR5cjhkNEdqbA/callback?with_response=false","stack":"DiscordAPIError[40060]: Interaction has already been acknowledged.\n    at handleErrors (/usr/src/app/node_modules/.pnpm/@discordjs+rest@2.4.2/node_modules/@discordjs/rest/dist/index.js:727:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async BurstHandler.runRequest (/usr/src/app/node_modules/.pnpm/@discordjs+rest@2.4.2/node_modules/@discordjs/rest/dist/index.js:831:23)\n    at async _REST.request (/usr/src/app/node_modules/.pnpm/@discordjs+rest@2.4.2/node_modules/@discordjs/rest/dist/index.js:1272:22)\n    at async ChatInputCommandInteraction.reply (/usr/src/app/node_modules/.pnpm/discord.js@14.17.3/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:194:22)\n    at async RecordCommand.execute (file:///usr/src/app/src/commands/audio/RecordCommand.js:54:17)\n    at async CommandRegistry.handleCommand (file:///usr/src/app/src/commands/audio/CommandRegistry.js:65:13)\n    at async Bot.handleInteraction (file:///usr/src/app/src/bot.js:77:13)"}
2025-01-19T06:40:52.418Z [31merror[39m: [VoiceRecorder] Error processing recording: fsSync is not defined{"stack":"ReferenceError: fsSync is not defined\n    at AudioService.convertToMp3 (file:///usr/src/app/src/services/AudioService.js:108:34)\n    at async VoiceRecorder.processRotatedRecording (file:///usr/src/app/src/VoiceRecorder.js:99:29)"}
2025-01-19T06:40:52.420Z [31merror[39m: [VoiceRecorder] Error processing rotated recording: fsSync is not defined{"stack":"ReferenceError: fsSync is not defined\n    at AudioService.convertToMp3 (file:///usr/src/app/src/services/AudioService.js:108:34)\n    at async VoiceRecorder.processRotatedRecording (file:///usr/src/app/src/VoiceRecorder.js:99:29)"}
2025-01-19T06:42:54.438Z [31merror[39m: [VoiceStateService] Connection error for guild 1315144523336122469: Unexpected server response: 500{"stack":"Error: Unexpected server response: 500\n    at ClientRequest.<anonymous> (/usr/src/app/node_modules/.pnpm/ws@8.18.0/node_modules/ws/lib/websocket.js:913:7)\n    at ClientRequest.emit (node:events:517:28)\n    at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:700:27)\n    at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)\n    at TLSSocket.socketOnData (node:_http_client:541:22)\n    at TLSSocket.emit (node:events:517:28)\n    at addChunk (node:internal/streams/readable:368:12)\n    at readableAddChunk (node:internal/streams/readable:341:9)\n    at Readable.push (node:internal/streams/readable:278:10)\n    at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23)"}
2025-01-19T06:47:17.464Z [31merror[39m: [VoiceRecorder] Error processing recording: this.transcriptionService.transcribeAudio is not a function{"stack":"TypeError: this.transcriptionService.transcribeAudio is not a function\n    at VoiceRecorder.processRotatedRecording (file:///usr/src/app/src/VoiceRecorder.js:109:64)"}
2025-01-19T06:47:17.466Z [31merror[39m: [VoiceRecorder] Error processing rotated recording: this.transcriptionService.transcribeAudio is not a function{"stack":"TypeError: this.transcriptionService.transcribeAudio is not a function\n    at VoiceRecorder.processRotatedRecording (file:///usr/src/app/src/VoiceRecorder.js:109:64)"}
2025-01-19T06:49:16.633Z [31merror[39m: [VoiceRecorder] Error processing recording: this.transcriptionService.transcribeAudio is not a function{"stack":"TypeError: this.transcriptionService.transcribeAudio is not a function\n    at VoiceRecorder.processRotatedRecording (file:///usr/src/app/src/VoiceRecorder.js:109:64)"}
2025-01-19T06:49:16.633Z [31merror[39m: [VoiceRecorder] Error processing rotated recording: this.transcriptionService.transcribeAudio is not a function{"stack":"TypeError: this.transcriptionService.transcribeAudio is not a function\n    at VoiceRecorder.processRotatedRecording (file:///usr/src/app/src/VoiceRecorder.js:109:64)"}
2025-01-19T06:51:21.577Z [31merror[39m: Error executing command record: Unknown interaction{"requestBody":{"json":{"type":5,"data":{"flags":0}}},"rawError":{"message":"Unknown interaction","code":10062},"code":10062,"status":404,"method":"POST","url":"https://discord.com/api/v10/interactions/1330429375270879255/aW50ZXJhY3Rpb246MTMzMDQyOTM3NTI3MDg3OTI1NTpGMEgxVThLS2psRkdsSWFadHA2bExFcExoV3BId1poM1RxY1dQanBOQ3NJMWJmRkVROGl5VXpsbGh0c1l4NTFPS1RmckROSlJkZGo1RElxR1BaNElkazBubk5ld1hnVzJLbGRsREd0YWNQbE9rOUdkRnRyc25kcjJVSVNQMUx2OA/callback?with_response=false","stack":"DiscordAPIError[10062]: Unknown interaction\n    at handleErrors (/usr/src/app/node_modules/.pnpm/@discordjs+rest@2.4.2/node_modules/@discordjs/rest/dist/index.js:727:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async BurstHandler.runRequest (/usr/src/app/node_modules/.pnpm/@discordjs+rest@2.4.2/node_modules/@discordjs/rest/dist/index.js:831:23)\n    at async _REST.request (/usr/src/app/node_modules/.pnpm/@discordjs+rest@2.4.2/node_modules/@discordjs/rest/dist/index.js:1272:22)\n    at async ChatInputCommandInteraction.deferReply (/usr/src/app/node_modules/.pnpm/discord.js@14.17.3/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:123:22)\n    at async RecordCommand.deferReplyIfNeeded (file:///usr/src/app/src/commands/audio/BaseCommand.js:21:17)\n    at async RecordCommand.execute (file:///usr/src/app/src/commands/audio/RecordCommand.js:28:13)\n    at async CommandRegistry.handleCommand (file:///usr/src/app/src/commands/audio/CommandRegistry.js:65:13)\n    at async Bot.handleInteraction (file:///usr/src/app/src/bot.js:77:13)"}
2025-01-19T06:51:21.579Z [31merror[39m: Error handling command: Unknown interaction{"requestBody":{"json":{"type":5,"data":{"flags":0}}},"rawError":{"message":"Unknown interaction","code":10062},"code":10062,"status":404,"method":"POST","url":"https://discord.com/api/v10/interactions/1330429375270879255/aW50ZXJhY3Rpb246MTMzMDQyOTM3NTI3MDg3OTI1NTpGMEgxVThLS2psRkdsSWFadHA2bExFcExoV3BId1poM1RxY1dQanBOQ3NJMWJmRkVROGl5VXpsbGh0c1l4NTFPS1RmckROSlJkZGo1RElxR1BaNElkazBubk5ld1hnVzJLbGRsREd0YWNQbE9rOUdkRnRyc25kcjJVSVNQMUx2OA/callback?with_response=false","stack":"DiscordAPIError[10062]: Unknown interaction\n    at handleErrors (/usr/src/app/node_modules/.pnpm/@discordjs+rest@2.4.2/node_modules/@discordjs/rest/dist/index.js:727:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async BurstHandler.runRequest (/usr/src/app/node_modules/.pnpm/@discordjs+rest@2.4.2/node_modules/@discordjs/rest/dist/index.js:831:23)\n    at async _REST.request (/usr/src/app/node_modules/.pnpm/@discordjs+rest@2.4.2/node_modules/@discordjs/rest/dist/index.js:1272:22)\n    at async ChatInputCommandInteraction.deferReply (/usr/src/app/node_modules/.pnpm/discord.js@14.17.3/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:123:22)\n    at async RecordCommand.deferReplyIfNeeded (file:///usr/src/app/src/commands/audio/BaseCommand.js:21:17)\n    at async RecordCommand.execute (file:///usr/src/app/src/commands/audio/RecordCommand.js:28:13)\n    at async CommandRegistry.handleCommand (file:///usr/src/app/src/commands/audio/CommandRegistry.js:65:13)\n    at async Bot.handleInteraction (file:///usr/src/app/src/bot.js:77:13)"}
2025-01-19T06:53:47.272Z [31merror[39m: Error executing command record: Unknown interaction{"requestBody":{"json":{"type":5,"data":{"flags":0}}},"rawError":{"message":"Unknown interaction","code":10062},"code":10062,"status":404,"method":"POST","url":"https://discord.com/api/v10/interactions/1330429986351484951/aW50ZXJhY3Rpb246MTMzMDQyOTk4NjM1MTQ4NDk1MTpaM0RRRDhzSDQ2QW1yYUVQbEx3MU1Ic3ljSExXc0RxV0hta2M1M3ZMdlBrblY5V0dFeW5PVnVwbVZVN0RLbTVaZGFpRmtXS0w1dE9uMkEzZnVJYUJaa1hCdG00N1ViYXE1Zk00bkxQTkx0SEJnNHE0TGE1bktZZzNsVXlmZEZJSg/callback?with_response=false","stack":"DiscordAPIError[10062]: Unknown interaction\n    at handleErrors (/usr/src/app/node_modules/.pnpm/@discordjs+rest@2.4.2/node_modules/@discordjs/rest/dist/index.js:727:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async BurstHandler.runRequest (/usr/src/app/node_modules/.pnpm/@discordjs+rest@2.4.2/node_modules/@discordjs/rest/dist/index.js:831:23)\n    at async _REST.request (/usr/src/app/node_modules/.pnpm/@discordjs+rest@2.4.2/node_modules/@discordjs/rest/dist/index.js:1272:22)\n    at async ChatInputCommandInteraction.deferReply (/usr/src/app/node_modules/.pnpm/discord.js@14.17.3/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:123:22)\n    at async RecordCommand.deferReplyIfNeeded (file:///usr/src/app/src/commands/audio/BaseCommand.js:21:17)\n    at async RecordCommand.execute (file:///usr/src/app/src/commands/audio/RecordCommand.js:28:13)\n    at async CommandRegistry.handleCommand (file:///usr/src/app/src/commands/audio/CommandRegistry.js:65:13)\n    at async Bot.handleInteraction (file:///usr/src/app/src/bot.js:77:13)"}
2025-01-19T06:53:47.275Z [31merror[39m: Error handling command: Unknown interaction{"requestBody":{"json":{"type":5,"data":{"flags":0}}},"rawError":{"message":"Unknown interaction","code":10062},"code":10062,"status":404,"method":"POST","url":"https://discord.com/api/v10/interactions/1330429986351484951/aW50ZXJhY3Rpb246MTMzMDQyOTk4NjM1MTQ4NDk1MTpaM0RRRDhzSDQ2QW1yYUVQbEx3MU1Ic3ljSExXc0RxV0hta2M1M3ZMdlBrblY5V0dFeW5PVnVwbVZVN0RLbTVaZGFpRmtXS0w1dE9uMkEzZnVJYUJaa1hCdG00N1ViYXE1Zk00bkxQTkx0SEJnNHE0TGE1bktZZzNsVXlmZEZJSg/callback?with_response=false","stack":"DiscordAPIError[10062]: Unknown interaction\n    at handleErrors (/usr/src/app/node_modules/.pnpm/@discordjs+rest@2.4.2/node_modules/@discordjs/rest/dist/index.js:727:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async BurstHandler.runRequest (/usr/src/app/node_modules/.pnpm/@discordjs+rest@2.4.2/node_modules/@discordjs/rest/dist/index.js:831:23)\n    at async _REST.request (/usr/src/app/node_modules/.pnpm/@discordjs+rest@2.4.2/node_modules/@discordjs/rest/dist/index.js:1272:22)\n    at async ChatInputCommandInteraction.deferReply (/usr/src/app/node_modules/.pnpm/discord.js@14.17.3/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:123:22)\n    at async RecordCommand.deferReplyIfNeeded (file:///usr/src/app/src/commands/audio/BaseCommand.js:21:17)\n    at async RecordCommand.execute (file:///usr/src/app/src/commands/audio/RecordCommand.js:28:13)\n    at async CommandRegistry.handleCommand (file:///usr/src/app/src/commands/audio/CommandRegistry.js:65:13)\n    at async Bot.handleInteraction (file:///usr/src/app/src/bot.js:77:13)"}
2025-01-19T06:58:38.547Z [31merror[39m: [TranscriptionService] Transcription failed: this.configService.getOpenAIKey is not a function{"stack":"TypeError: this.configService.getOpenAIKey is not a function\n    at TranscriptionService.transcribe (file:///usr/src/app/src/services/TranscriptionService.js:15:47)\n    at VoiceRecorder.processRotatedRecording (file:///usr/src/app/src/VoiceRecorder.js:109:64)"}
2025-01-19T06:58:38.548Z [31merror[39m: [VoiceRecorder] Error processing recording: this.configService.getOpenAIKey is not a function{"stack":"TypeError: this.configService.getOpenAIKey is not a function\n    at TranscriptionService.transcribe (file:///usr/src/app/src/services/TranscriptionService.js:15:47)\n    at VoiceRecorder.processRotatedRecording (file:///usr/src/app/src/VoiceRecorder.js:109:64)"}
2025-01-19T06:58:38.548Z [31merror[39m: [VoiceRecorder] Error processing rotated recording: this.configService.getOpenAIKey is not a function{"stack":"TypeError: this.configService.getOpenAIKey is not a function\n    at TranscriptionService.transcribe (file:///usr/src/app/src/services/TranscriptionService.js:15:47)\n    at VoiceRecorder.processRotatedRecording (file:///usr/src/app/src/VoiceRecorder.js:109:64)"}
2025-01-19T07:00:38.109Z [31merror[39m: [TranscriptionService] Transcription failed: this.configService.getOpenAIKey is not a function{"stack":"TypeError: this.configService.getOpenAIKey is not a function\n    at TranscriptionService.transcribe (file:///usr/src/app/src/services/TranscriptionService.js:15:47)\n    at VoiceRecorder.processRotatedRecording (file:///usr/src/app/src/VoiceRecorder.js:109:64)"}
2025-01-19T07:00:38.110Z [31merror[39m: [VoiceRecorder] Error processing recording: this.configService.getOpenAIKey is not a function{"stack":"TypeError: this.configService.getOpenAIKey is not a function\n    at TranscriptionService.transcribe (file:///usr/src/app/src/services/TranscriptionService.js:15:47)\n    at VoiceRecorder.processRotatedRecording (file:///usr/src/app/src/VoiceRecorder.js:109:64)"}
2025-01-19T07:00:38.110Z [31merror[39m: [VoiceRecorder] Error processing rotated recording: this.configService.getOpenAIKey is not a function{"stack":"TypeError: this.configService.getOpenAIKey is not a function\n    at TranscriptionService.transcribe (file:///usr/src/app/src/services/TranscriptionService.js:15:47)\n    at VoiceRecorder.processRotatedRecording (file:///usr/src/app/src/VoiceRecorder.js:109:64)"}
2025-01-19T07:02:38.575Z [31merror[39m: [TranscriptionService] Transcription failed: this.configService.getOpenAIKey is not a function{"stack":"TypeError: this.configService.getOpenAIKey is not a function\n    at TranscriptionService.transcribe (file:///usr/src/app/src/services/TranscriptionService.js:15:47)\n    at VoiceRecorder.processRotatedRecording (file:///usr/src/app/src/VoiceRecorder.js:109:64)"}
2025-01-19T07:02:38.577Z [31merror[39m: [VoiceRecorder] Error processing recording: this.configService.getOpenAIKey is not a function{"stack":"TypeError: this.configService.getOpenAIKey is not a function\n    at TranscriptionService.transcribe (file:///usr/src/app/src/services/TranscriptionService.js:15:47)\n    at VoiceRecorder.processRotatedRecording (file:///usr/src/app/src/VoiceRecorder.js:109:64)"}
2025-01-19T07:02:38.578Z [31merror[39m: [VoiceRecorder] Error processing rotated recording: this.configService.getOpenAIKey is not a function{"stack":"TypeError: this.configService.getOpenAIKey is not a function\n    at TranscriptionService.transcribe (file:///usr/src/app/src/services/TranscriptionService.js:15:47)\n    at VoiceRecorder.processRotatedRecording (file:///usr/src/app/src/VoiceRecorder.js:109:64)"}
2025-01-19T18:24:07.487Z [31merror[39m: [TranscriptionService] Transcription failed: Cannot read properties of undefined (reading 'TRANSCRIPTION_PROMPT'){"stack":"TypeError: Cannot read properties of undefined (reading 'TRANSCRIPTION_PROMPT')\n    at TranscriptionService.transcribe (file:///usr/src/app/src/services/TranscriptionService.js:39:37)\n    at async VoiceRecorder.processRotatedRecording (file:///usr/src/app/src/VoiceRecorder.js:109:32)"}
2025-01-19T18:24:07.488Z [31merror[39m: [VoiceRecorder] Error processing recording: Cannot read properties of undefined (reading 'TRANSCRIPTION_PROMPT'){"stack":"TypeError: Cannot read properties of undefined (reading 'TRANSCRIPTION_PROMPT')\n    at TranscriptionService.transcribe (file:///usr/src/app/src/services/TranscriptionService.js:39:37)\n    at async VoiceRecorder.processRotatedRecording (file:///usr/src/app/src/VoiceRecorder.js:109:32)"}
2025-01-19T18:24:07.489Z [31merror[39m: [VoiceRecorder] Error processing rotated recording: Cannot read properties of undefined (reading 'TRANSCRIPTION_PROMPT'){"stack":"TypeError: Cannot read properties of undefined (reading 'TRANSCRIPTION_PROMPT')\n    at TranscriptionService.transcribe (file:///usr/src/app/src/services/TranscriptionService.js:39:37)\n    at async VoiceRecorder.processRotatedRecording (file:///usr/src/app/src/VoiceRecorder.js:109:32)"}
2025-01-19T18:27:06.498Z [31merror[39m: [TranscriptionService] Transcription failed: Cannot read properties of undefined (reading 'TRANSCRIPTION_PROMPT'){"stack":"TypeError: Cannot read properties of undefined (reading 'TRANSCRIPTION_PROMPT')\n    at TranscriptionService.transcribe (file:///usr/src/app/src/services/TranscriptionService.js:39:37)\n    at async VoiceRecorder.processRotatedRecording (file:///usr/src/app/src/VoiceRecorder.js:109:32)"}
2025-01-19T18:27:06.499Z [31merror[39m: [VoiceRecorder] Error processing recording: Cannot read properties of undefined (reading 'TRANSCRIPTION_PROMPT'){"stack":"TypeError: Cannot read properties of undefined (reading 'TRANSCRIPTION_PROMPT')\n    at TranscriptionService.transcribe (file:///usr/src/app/src/services/TranscriptionService.js:39:37)\n    at async VoiceRecorder.processRotatedRecording (file:///usr/src/app/src/VoiceRecorder.js:109:32)"}
2025-01-19T18:27:06.500Z [31merror[39m: [VoiceRecorder] Error processing rotated recording: Cannot read properties of undefined (reading 'TRANSCRIPTION_PROMPT'){"stack":"TypeError: Cannot read properties of undefined (reading 'TRANSCRIPTION_PROMPT')\n    at TranscriptionService.transcribe (file:///usr/src/app/src/services/TranscriptionService.js:39:37)\n    at async VoiceRecorder.processRotatedRecording (file:///usr/src/app/src/VoiceRecorder.js:109:32)"}
2025-01-19T18:28:37.053Z [31merror[39m: Error executing command record: Unknown interaction{"requestBody":{"json":{"type":5,"data":{"flags":0}}},"rawError":{"message":"Unknown interaction","code":10062},"code":10062,"status":404,"method":"POST","url":"https://discord.com/api/v10/interactions/1330604846222544896/aW50ZXJhY3Rpb246MTMzMDYwNDg0NjIyMjU0NDg5NjpnOGxCQVp0R0JhWlZ0M3hTQmdheTRBRHlCb21mdExyejU5aEhYN0w0dG9uOGZxMHpxYktiYURWTDhxVngxR1lSVkFkVzNKUzdmSm1VVHpCU2FXTkd3SnhmTElXVTZnQURsMDVpVElhWmNvMTBCbE9WSjJOQTQ2d3diZU40WXVlSw/callback?with_response=false","stack":"DiscordAPIError[10062]: Unknown interaction\n    at handleErrors (/usr/src/app/node_modules/.pnpm/@discordjs+rest@2.4.2/node_modules/@discordjs/rest/dist/index.js:727:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async BurstHandler.runRequest (/usr/src/app/node_modules/.pnpm/@discordjs+rest@2.4.2/node_modules/@discordjs/rest/dist/index.js:831:23)\n    at async _REST.request (/usr/src/app/node_modules/.pnpm/@discordjs+rest@2.4.2/node_modules/@discordjs/rest/dist/index.js:1272:22)\n    at async ChatInputCommandInteraction.deferReply (/usr/src/app/node_modules/.pnpm/discord.js@14.17.3/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:123:22)\n    at async RecordCommand.deferReplyIfNeeded (file:///usr/src/app/src/commands/audio/BaseCommand.js:21:17)\n    at async RecordCommand.execute (file:///usr/src/app/src/commands/audio/RecordCommand.js:27:13)\n    at async CommandRegistry.handleCommand (file:///usr/src/app/src/commands/audio/CommandRegistry.js:65:13)\n    at async Bot.handleInteraction (file:///usr/src/app/src/bot.js:77:13)"}
2025-01-19T18:28:37.054Z [31merror[39m: Error handling command: Unknown interaction{"requestBody":{"json":{"type":5,"data":{"flags":0}}},"rawError":{"message":"Unknown interaction","code":10062},"code":10062,"status":404,"method":"POST","url":"https://discord.com/api/v10/interactions/1330604846222544896/aW50ZXJhY3Rpb246MTMzMDYwNDg0NjIyMjU0NDg5NjpnOGxCQVp0R0JhWlZ0M3hTQmdheTRBRHlCb21mdExyejU5aEhYN0w0dG9uOGZxMHpxYktiYURWTDhxVngxR1lSVkFkVzNKUzdmSm1VVHpCU2FXTkd3SnhmTElXVTZnQURsMDVpVElhWmNvMTBCbE9WSjJOQTQ2d3diZU40WXVlSw/callback?with_response=false","stack":"DiscordAPIError[10062]: Unknown interaction\n    at handleErrors (/usr/src/app/node_modules/.pnpm/@discordjs+rest@2.4.2/node_modules/@discordjs/rest/dist/index.js:727:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async BurstHandler.runRequest (/usr/src/app/node_modules/.pnpm/@discordjs+rest@2.4.2/node_modules/@discordjs/rest/dist/index.js:831:23)\n    at async _REST.request (/usr/src/app/node_modules/.pnpm/@discordjs+rest@2.4.2/node_modules/@discordjs/rest/dist/index.js:1272:22)\n    at async ChatInputCommandInteraction.deferReply (/usr/src/app/node_modules/.pnpm/discord.js@14.17.3/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:123:22)\n    at async RecordCommand.deferReplyIfNeeded (file:///usr/src/app/src/commands/audio/BaseCommand.js:21:17)\n    at async RecordCommand.execute (file:///usr/src/app/src/commands/audio/RecordCommand.js:27:13)\n    at async CommandRegistry.handleCommand (file:///usr/src/app/src/commands/audio/CommandRegistry.js:65:13)\n    at async Bot.handleInteraction (file:///usr/src/app/src/bot.js:77:13)"}
2025-01-19T18:38:02.547Z [31merror[39m: Failed to send error response: The reply to this interaction has not been sent or deferred.{"code":"InteractionNotReplied","stack":"Error [InteractionNotReplied]: The reply to this interaction has not been sent or deferred.\n    at ChatInputCommandInteraction.editReply (/usr/src/app/node_modules/.pnpm/discord.js@14.17.3/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:247:48)\n    at RecordCommand.execute (file:///usr/src/app/src/commands/audio/RecordCommand.js:56:35)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async CommandRegistry.handleCommand (file:///usr/src/app/src/commands/audio/CommandRegistry.js:65:13)\n    at async Bot.handleInteraction (file:///usr/src/app/src/bot.js:77:13)"}
2025-01-19T18:38:02.549Z [31merror[39m: Error executing command record: Unknown interaction{"requestBody":{"json":{"type":5,"data":{"flags":0}}},"rawError":{"message":"Unknown interaction","code":10062},"code":10062,"status":404,"method":"POST","url":"https://discord.com/api/v10/interactions/1330607218336333855/aW50ZXJhY3Rpb246MTMzMDYwNzIxODMzNjMzMzg1NTpQdVJ3RXZlWXNzdllISm12YWpNZENvM3BCN3oxV2ZrbU95emFMc2oyN0E0Ylc5MEFMRjVUMWNxVWJaajBJMnFtanVkQk90QVFWM05yTHpLR2t1VlBvYTFwMWNIMTRkWU1wN3ZGZU5JSDBERzQ3ZWFOb09DQW5XaVltTTgxU2Ewbg/callback?with_response=false","stack":"DiscordAPIError[10062]: Unknown interaction\n    at handleErrors (/usr/src/app/node_modules/.pnpm/@discordjs+rest@2.4.2/node_modules/@discordjs/rest/dist/index.js:727:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async BurstHandler.runRequest (/usr/src/app/node_modules/.pnpm/@discordjs+rest@2.4.2/node_modules/@discordjs/rest/dist/index.js:831:23)\n    at async _REST.request (/usr/src/app/node_modules/.pnpm/@discordjs+rest@2.4.2/node_modules/@discordjs/rest/dist/index.js:1272:22)\n    at async ChatInputCommandInteraction.deferReply (/usr/src/app/node_modules/.pnpm/discord.js@14.17.3/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:123:22)\n    at async RecordCommand.deferReplyIfNeeded (file:///usr/src/app/src/commands/audio/BaseCommand.js:21:17)\n    at async RecordCommand.execute (file:///usr/src/app/src/commands/audio/RecordCommand.js:27:13)\n    at async CommandRegistry.handleCommand (file:///usr/src/app/src/commands/audio/CommandRegistry.js:65:13)\n    at async Bot.handleInteraction (file:///usr/src/app/src/bot.js:77:13)"}
2025-01-19T18:38:02.551Z [31merror[39m: Error handling command: Unknown interaction{"requestBody":{"json":{"type":5,"data":{"flags":0}}},"rawError":{"message":"Unknown interaction","code":10062},"code":10062,"status":404,"method":"POST","url":"https://discord.com/api/v10/interactions/1330607218336333855/aW50ZXJhY3Rpb246MTMzMDYwNzIxODMzNjMzMzg1NTpQdVJ3RXZlWXNzdllISm12YWpNZENvM3BCN3oxV2ZrbU95emFMc2oyN0E0Ylc5MEFMRjVUMWNxVWJaajBJMnFtanVkQk90QVFWM05yTHpLR2t1VlBvYTFwMWNIMTRkWU1wN3ZGZU5JSDBERzQ3ZWFOb09DQW5XaVltTTgxU2Ewbg/callback?with_response=false","stack":"DiscordAPIError[10062]: Unknown interaction\n    at handleErrors (/usr/src/app/node_modules/.pnpm/@discordjs+rest@2.4.2/node_modules/@discordjs/rest/dist/index.js:727:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async BurstHandler.runRequest (/usr/src/app/node_modules/.pnpm/@discordjs+rest@2.4.2/node_modules/@discordjs/rest/dist/index.js:831:23)\n    at async _REST.request (/usr/src/app/node_modules/.pnpm/@discordjs+rest@2.4.2/node_modules/@discordjs/rest/dist/index.js:1272:22)\n    at async ChatInputCommandInteraction.deferReply (/usr/src/app/node_modules/.pnpm/discord.js@14.17.3/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:123:22)\n    at async RecordCommand.deferReplyIfNeeded (file:///usr/src/app/src/commands/audio/BaseCommand.js:21:17)\n    at async RecordCommand.execute (file:///usr/src/app/src/commands/audio/RecordCommand.js:27:13)\n    at async CommandRegistry.handleCommand (file:///usr/src/app/src/commands/audio/CommandRegistry.js:65:13)\n    at async Bot.handleInteraction (file:///usr/src/app/src/bot.js:77:13)"}
2025-01-19T18:38:02.553Z [31merror[39m: Discord client error: Unknown interaction{"requestBody":{"json":{"type":5,"data":{"flags":0}}},"rawError":{"message":"Unknown interaction","code":10062},"code":10062,"status":404,"method":"POST","url":"https://discord.com/api/v10/interactions/1330607218336333855/aW50ZXJhY3Rpb246MTMzMDYwNzIxODMzNjMzMzg1NTpQdVJ3RXZlWXNzdllISm12YWpNZENvM3BCN3oxV2ZrbU95emFMc2oyN0E0Ylc5MEFMRjVUMWNxVWJaajBJMnFtanVkQk90QVFWM05yTHpLR2t1VlBvYTFwMWNIMTRkWU1wN3ZGZU5JSDBERzQ3ZWFOb09DQW5XaVltTTgxU2Ewbg/callback?with_response=false","stack":"DiscordAPIError[10062]: Unknown interaction\n    at handleErrors (/usr/src/app/node_modules/.pnpm/@discordjs+rest@2.4.2/node_modules/@discordjs/rest/dist/index.js:727:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async BurstHandler.runRequest (/usr/src/app/node_modules/.pnpm/@discordjs+rest@2.4.2/node_modules/@discordjs/rest/dist/index.js:831:23)\n    at async _REST.request (/usr/src/app/node_modules/.pnpm/@discordjs+rest@2.4.2/node_modules/@discordjs/rest/dist/index.js:1272:22)\n    at async ChatInputCommandInteraction.deferReply (/usr/src/app/node_modules/.pnpm/discord.js@14.17.3/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:123:22)\n    at async RecordCommand.deferReplyIfNeeded (file:///usr/src/app/src/commands/audio/BaseCommand.js:21:17)\n    at async RecordCommand.execute (file:///usr/src/app/src/commands/audio/RecordCommand.js:27:13)\n    at async CommandRegistry.handleCommand (file:///usr/src/app/src/commands/audio/CommandRegistry.js:65:13)\n    at async Bot.handleInteraction (file:///usr/src/app/src/bot.js:77:13)"}
2025-01-19T18:47:02.160Z [31merror[39m: [TranscriptionService] Summary generation failed:{"location":"TranscriptionService.generateSummary","error":{"name":"Error","message":"Failed to generate summary","stack":"Error: Failed to generate summary\n    at TranscriptionService.generateSummary (file:///usr/src/app/src/services/TranscriptionService.js:104:31)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async VoiceRecorder.processRotatedRecording (file:///usr/src/app/src/VoiceRecorder.js:116:27)"},"context":{"transcriptLength":45,"transcriptSample":"Do do do do do do do do. It's not, it's not.\n"}}
2025-01-19T18:47:15.771Z [31merror[39m: [TranscriptionService] Summary generation failed:{"location":"TranscriptionService.generateSummary","error":{"name":"Error","message":"Failed to generate summary","stack":"Error: Failed to generate summary\n    at TranscriptionService.generateSummary (file:///usr/src/app/src/services/TranscriptionService.js:104:31)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async file:///usr/src/app/src/services/SummaryJobService.js:24:33\n    at async Queue.<anonymous> (file:///usr/src/app/src/services/JobService.js:44:24)"},"context":{"transcriptLength":45,"transcriptSample":"Do do do do do do do do. It's not, it's not.\n"}}
2025-01-19T18:47:15.772Z [31merror[39m: [SummaryJobService] Failed to generate background summary:{"error":"Failed to generate summary: Failed to generate summary","stack":"Error: Failed to generate summary: Failed to generate summary\n    at TranscriptionService.generateSummary (file:///usr/src/app/src/services/TranscriptionService.js:150:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async file:///usr/src/app/src/services/SummaryJobService.js:24:33\n    at async Queue.<anonymous> (file:///usr/src/app/src/services/JobService.js:44:24)","guildId":"1315144523336122469"}
2025-01-19T18:47:15.772Z [31merror[39m: [JobService] Error processing job in queue summary-generation:{"jobId":"1","error":"Failed to generate summary: Failed to generate summary","stack":"Error: Failed to generate summary: Failed to generate summary\n    at TranscriptionService.generateSummary (file:///usr/src/app/src/services/TranscriptionService.js:150:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async file:///usr/src/app/src/services/SummaryJobService.js:24:33\n    at async Queue.<anonymous> (file:///usr/src/app/src/services/JobService.js:44:24)"}
2025-01-19T18:47:15.785Z [31merror[39m: [JobService] Job failed in queue summary-generation:{"jobId":"1","error":"Failed to generate summary: Failed to generate summary","stack":"Error: Failed to generate summary: Failed to generate summary\n    at TranscriptionService.generateSummary (file:///usr/src/app/src/services/TranscriptionService.js:150:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async file:///usr/src/app/src/services/SummaryJobService.js:24:33\n    at async Queue.<anonymous> (file:///usr/src/app/src/services/JobService.js:44:24)","attempts":1}
2025-01-19T18:47:41.770Z [31merror[39m: Failed to send error response: The reply to this interaction has not been sent or deferred.{"code":"InteractionNotReplied","stack":"Error [InteractionNotReplied]: The reply to this interaction has not been sent or deferred.\n    at ChatInputCommandInteraction.editReply (/usr/src/app/node_modules/.pnpm/discord.js@14.17.3/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:247:48)\n    at RecordCommand.execute (file:///usr/src/app/src/commands/audio/RecordCommand.js:58:35)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async CommandRegistry.handleCommand (file:///usr/src/app/src/commands/audio/CommandRegistry.js:65:13)\n    at async Bot.handleInteraction (file:///usr/src/app/src/bot.js:77:13)"}
2025-01-19T18:47:41.772Z [31merror[39m: Error executing command record: Unknown interaction{"requestBody":{"json":{"type":5,"data":{"flags":0}}},"rawError":{"message":"Unknown interaction","code":10062},"code":10062,"status":404,"method":"POST","url":"https://discord.com/api/v10/interactions/1330609648134520944/aW50ZXJhY3Rpb246MTMzMDYwOTY0ODEzNDUyMDk0NDpHd2djWnJtM3gwcktrQ2FQQW4zSUN3RG5EYzRSN1RYT1RvY2FPZndTTmRqR2Rud2Q0SjEyajMwR3EySXhEYnFSZ0UyV1E5djFMa0Uyck1vYVZJY1djRmRzNjBGeDFDd2E0ZVBKMEwzcGlQMVY2dlhhbThtZWZiOVVSMm1vZWV6WA/callback?with_response=false","stack":"DiscordAPIError[10062]: Unknown interaction\n    at handleErrors (/usr/src/app/node_modules/.pnpm/@discordjs+rest@2.4.2/node_modules/@discordjs/rest/dist/index.js:727:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async BurstHandler.runRequest (/usr/src/app/node_modules/.pnpm/@discordjs+rest@2.4.2/node_modules/@discordjs/rest/dist/index.js:831:23)\n    at async _REST.request (/usr/src/app/node_modules/.pnpm/@discordjs+rest@2.4.2/node_modules/@discordjs/rest/dist/index.js:1272:22)\n    at async ChatInputCommandInteraction.deferReply (/usr/src/app/node_modules/.pnpm/discord.js@14.17.3/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:123:22)\n    at async RecordCommand.deferReplyIfNeeded (file:///usr/src/app/src/commands/audio/BaseCommand.js:21:17)\n    at async RecordCommand.execute (file:///usr/src/app/src/commands/audio/RecordCommand.js:21:13)\n    at async CommandRegistry.handleCommand (file:///usr/src/app/src/commands/audio/CommandRegistry.js:65:13)\n    at async Bot.handleInteraction (file:///usr/src/app/src/bot.js:77:13)"}
2025-01-19T18:47:41.773Z [31merror[39m: Error handling command: Unknown interaction{"requestBody":{"json":{"type":5,"data":{"flags":0}}},"rawError":{"message":"Unknown interaction","code":10062},"code":10062,"status":404,"method":"POST","url":"https://discord.com/api/v10/interactions/1330609648134520944/aW50ZXJhY3Rpb246MTMzMDYwOTY0ODEzNDUyMDk0NDpHd2djWnJtM3gwcktrQ2FQQW4zSUN3RG5EYzRSN1RYT1RvY2FPZndTTmRqR2Rud2Q0SjEyajMwR3EySXhEYnFSZ0UyV1E5djFMa0Uyck1vYVZJY1djRmRzNjBGeDFDd2E0ZVBKMEwzcGlQMVY2dlhhbThtZWZiOVVSMm1vZWV6WA/callback?with_response=false","stack":"DiscordAPIError[10062]: Unknown interaction\n    at handleErrors (/usr/src/app/node_modules/.pnpm/@discordjs+rest@2.4.2/node_modules/@discordjs/rest/dist/index.js:727:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async BurstHandler.runRequest (/usr/src/app/node_modules/.pnpm/@discordjs+rest@2.4.2/node_modules/@discordjs/rest/dist/index.js:831:23)\n    at async _REST.request (/usr/src/app/node_modules/.pnpm/@discordjs+rest@2.4.2/node_modules/@discordjs/rest/dist/index.js:1272:22)\n    at async ChatInputCommandInteraction.deferReply (/usr/src/app/node_modules/.pnpm/discord.js@14.17.3/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:123:22)\n    at async RecordCommand.deferReplyIfNeeded (file:///usr/src/app/src/commands/audio/BaseCommand.js:21:17)\n    at async RecordCommand.execute (file:///usr/src/app/src/commands/audio/RecordCommand.js:21:13)\n    at async CommandRegistry.handleCommand (file:///usr/src/app/src/commands/audio/CommandRegistry.js:65:13)\n    at async Bot.handleInteraction (file:///usr/src/app/src/bot.js:77:13)"}
2025-01-19T18:47:41.775Z [31merror[39m: Discord client error: Unknown interaction{"requestBody":{"json":{"type":5,"data":{"flags":0}}},"rawError":{"message":"Unknown interaction","code":10062},"code":10062,"status":404,"method":"POST","url":"https://discord.com/api/v10/interactions/1330609648134520944/aW50ZXJhY3Rpb246MTMzMDYwOTY0ODEzNDUyMDk0NDpHd2djWnJtM3gwcktrQ2FQQW4zSUN3RG5EYzRSN1RYT1RvY2FPZndTTmRqR2Rud2Q0SjEyajMwR3EySXhEYnFSZ0UyV1E5djFMa0Uyck1vYVZJY1djRmRzNjBGeDFDd2E0ZVBKMEwzcGlQMVY2dlhhbThtZWZiOVVSMm1vZWV6WA/callback?with_response=false","stack":"DiscordAPIError[10062]: Unknown interaction\n    at handleErrors (/usr/src/app/node_modules/.pnpm/@discordjs+rest@2.4.2/node_modules/@discordjs/rest/dist/index.js:727:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async BurstHandler.runRequest (/usr/src/app/node_modules/.pnpm/@discordjs+rest@2.4.2/node_modules/@discordjs/rest/dist/index.js:831:23)\n    at async _REST.request (/usr/src/app/node_modules/.pnpm/@discordjs+rest@2.4.2/node_modules/@discordjs/rest/dist/index.js:1272:22)\n    at async ChatInputCommandInteraction.deferReply (/usr/src/app/node_modules/.pnpm/discord.js@14.17.3/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:123:22)\n    at async RecordCommand.deferReplyIfNeeded (file:///usr/src/app/src/commands/audio/BaseCommand.js:21:17)\n    at async RecordCommand.execute (file:///usr/src/app/src/commands/audio/RecordCommand.js:21:13)\n    at async CommandRegistry.handleCommand (file:///usr/src/app/src/commands/audio/CommandRegistry.js:65:13)\n    at async Bot.handleInteraction (file:///usr/src/app/src/bot.js:77:13)"}
2025-01-19T18:49:15.372Z [31merror[39m: [TranscriptionService] Summary generation failed:{"location":"TranscriptionService.generateSummary","error":{"name":"Error","message":"Failed to generate summary","stack":"Error: Failed to generate summary\n    at TranscriptionService.generateSummary (file:///usr/src/app/src/services/TranscriptionService.js:104:31)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async file:///usr/src/app/src/services/SummaryJobService.js:24:33\n    at async Queue.<anonymous> (file:///usr/src/app/src/services/JobService.js:44:24)"},"context":{"transcriptLength":45,"transcriptSample":"Do do do do do do do do. It's not, it's not.\n"}}
2025-01-19T18:49:15.374Z [31merror[39m: [SummaryJobService] Failed to generate background summary:{"error":"Failed to generate summary: Failed to generate summary","stack":"Error: Failed to generate summary: Failed to generate summary\n    at TranscriptionService.generateSummary (file:///usr/src/app/src/services/TranscriptionService.js:150:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async file:///usr/src/app/src/services/SummaryJobService.js:24:33\n    at async Queue.<anonymous> (file:///usr/src/app/src/services/JobService.js:44:24)","guildId":"1315144523336122469"}
2025-01-19T18:49:15.376Z [31merror[39m: [JobService] Error processing job in queue summary-generation:{"jobId":"1","error":"Failed to generate summary: Failed to generate summary","stack":"Error: Failed to generate summary: Failed to generate summary\n    at TranscriptionService.generateSummary (file:///usr/src/app/src/services/TranscriptionService.js:150:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async file:///usr/src/app/src/services/SummaryJobService.js:24:33\n    at async Queue.<anonymous> (file:///usr/src/app/src/services/JobService.js:44:24)"}
2025-01-19T18:49:15.409Z [31merror[39m: [JobService] Job failed in queue summary-generation:{"jobId":"1","error":"Failed to generate summary: Failed to generate summary","stack":"Error: Failed to generate summary: Failed to generate summary\n    at TranscriptionService.generateSummary (file:///usr/src/app/src/services/TranscriptionService.js:150:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async file:///usr/src/app/src/services/SummaryJobService.js:24:33\n    at async Queue.<anonymous> (file:///usr/src/app/src/services/JobService.js:44:24)","attempts":2}
2025-01-19T18:49:32.334Z [31merror[39m: [TranscriptionService] Summary generation failed:{"location":"TranscriptionService.generateSummary","error":{"name":"Error","message":"Failed to generate summary","stack":"Error: Failed to generate summary\n    at TranscriptionService.generateSummary (file:///usr/src/app/src/services/TranscriptionService.js:104:31)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async file:///usr/src/app/src/services/SummaryJobService.js:24:33\n    at async Queue.<anonymous> (file:///usr/src/app/src/services/JobService.js:44:24)"},"context":{"transcriptLength":45,"transcriptSample":"Do do do do do do do do. It's not, it's not.\n"}}
2025-01-19T18:49:32.334Z [31merror[39m: [SummaryJobService] Failed to generate background summary:{"error":"Failed to generate summary: Failed to generate summary","stack":"Error: Failed to generate summary: Failed to generate summary\n    at TranscriptionService.generateSummary (file:///usr/src/app/src/services/TranscriptionService.js:150:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async file:///usr/src/app/src/services/SummaryJobService.js:24:33\n    at async Queue.<anonymous> (file:///usr/src/app/src/services/JobService.js:44:24)","guildId":"1315144523336122469"}
2025-01-19T18:49:32.335Z [31merror[39m: [JobService] Error processing job in queue summary-generation:{"jobId":"1","error":"Failed to generate summary: Failed to generate summary","stack":"Error: Failed to generate summary: Failed to generate summary\n    at TranscriptionService.generateSummary (file:///usr/src/app/src/services/TranscriptionService.js:150:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async file:///usr/src/app/src/services/SummaryJobService.js:24:33\n    at async Queue.<anonymous> (file:///usr/src/app/src/services/JobService.js:44:24)"}
2025-01-19T18:49:32.343Z [31merror[39m: [JobService] Job failed in queue summary-generation:{"jobId":"1","error":"Failed to generate summary: Failed to generate summary","stack":"Error: Failed to generate summary: Failed to generate summary\n    at TranscriptionService.generateSummary (file:///usr/src/app/src/services/TranscriptionService.js:150:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async file:///usr/src/app/src/services/SummaryJobService.js:24:33\n    at async Queue.<anonymous> (file:///usr/src/app/src/services/JobService.js:44:24)","attempts":3}
2025-01-19T18:58:25.497Z [31merror[39m: Error executing command record: The reply to this interaction has already been sent or deferred.{"code":"InteractionAlreadyReplied","stack":"Error [InteractionAlreadyReplied]: The reply to this interaction has already been sent or deferred.\n    at ChatInputCommandInteraction.reply (/usr/src/app/node_modules/.pnpm/discord.js@14.17.3/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:163:46)\n    at handleReply (file:///usr/src/app/src/utils/interactionHelper.js:9:31)\n    at RecordCommand.execute (file:///usr/src/app/src/commands/audio/RecordCommand.js:63:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async CommandRegistry.handleCommand (file:///usr/src/app/src/commands/audio/CommandRegistry.js:65:13)\n    at async Bot.handleInteraction (file:///usr/src/app/src/bot.js:77:13)"}
2025-01-19T18:58:25.498Z [31merror[39m: Error handling command: The reply to this interaction has already been sent or deferred.{"code":"InteractionAlreadyReplied","stack":"Error [InteractionAlreadyReplied]: The reply to this interaction has already been sent or deferred.\n    at ChatInputCommandInteraction.reply (/usr/src/app/node_modules/.pnpm/discord.js@14.17.3/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:163:46)\n    at handleReply (file:///usr/src/app/src/utils/interactionHelper.js:9:31)\n    at RecordCommand.execute (file:///usr/src/app/src/commands/audio/RecordCommand.js:63:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async CommandRegistry.handleCommand (file:///usr/src/app/src/commands/audio/CommandRegistry.js:65:13)\n    at async Bot.handleInteraction (file:///usr/src/app/src/bot.js:77:13)"}
2025-01-19T18:58:25.499Z [31merror[39m: Discord client error: The reply to this interaction has already been sent or deferred.{"code":"InteractionAlreadyReplied","stack":"Error [InteractionAlreadyReplied]: The reply to this interaction has already been sent or deferred.\n    at ChatInputCommandInteraction.reply (/usr/src/app/node_modules/.pnpm/discord.js@14.17.3/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:163:46)\n    at handleReply (file:///usr/src/app/src/utils/interactionHelper.js:9:31)\n    at RecordCommand.execute (file:///usr/src/app/src/commands/audio/RecordCommand.js:63:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async CommandRegistry.handleCommand (file:///usr/src/app/src/commands/audio/CommandRegistry.js:65:13)\n    at async Bot.handleInteraction (file:///usr/src/app/src/bot.js:77:13)"}
2025-01-19T19:01:01.992Z [31merror[39m: Error executing command record: Interaction has already been acknowledged.{"requestBody":{"files":[],"json":{"type":4,"data":{"content":"❌ Failed to start recording. Please try again.","tts":false,"enforce_nonce":false}}},"rawError":{"message":"Interaction has already been acknowledged.","code":40060},"code":40060,"status":400,"method":"POST","url":"https://discord.com/api/v10/interactions/1330613003279667362/aW50ZXJhY3Rpb246MTMzMDYxMzAwMzI3OTY2NzM2Mjo2UG5YOFJSRDVDUUhvb2xWTnIxdExHcVRBOERKOFF0bVhwQ3RUZ0FQeE5QQjV6WjJ1VWIyQnVaeEEyU0NQS2xOYzdQWk5WU0pxeVFjVDdPd0FQTWlzc3doWGhBbG5ibVVuQjRmOURmc0dqeWIyU21MMHVEVTVDQXhmSTluOWVicQ/callback?with_response=false","stack":"DiscordAPIError[40060]: Interaction has already been acknowledged.\n    at handleErrors (/usr/src/app/node_modules/.pnpm/@discordjs+rest@2.4.2/node_modules/@discordjs/rest/dist/index.js:727:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async BurstHandler.runRequest (/usr/src/app/node_modules/.pnpm/@discordjs+rest@2.4.2/node_modules/@discordjs/rest/dist/index.js:831:23)\n    at async _REST.request (/usr/src/app/node_modules/.pnpm/@discordjs+rest@2.4.2/node_modules/@discordjs/rest/dist/index.js:1272:22)\n    at async ChatInputCommandInteraction.reply (/usr/src/app/node_modules/.pnpm/discord.js@14.17.3/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:194:22)\n    at async handleReply (file:///usr/src/app/src/utils/interactionHelper.js:9:13)\n    at async RecordCommand.execute (file:///usr/src/app/src/commands/audio/RecordCommand.js:63:13)\n    at async CommandRegistry.handleCommand (file:///usr/src/app/src/commands/audio/CommandRegistry.js:65:13)\n    at async Bot.handleInteraction (file:///usr/src/app/src/bot.js:77:13)"}
2025-01-19T19:01:01.995Z [31merror[39m: Error handling command: Interaction has already been acknowledged.{"requestBody":{"files":[],"json":{"type":4,"data":{"content":"❌ Failed to start recording. Please try again.","tts":false,"enforce_nonce":false}}},"rawError":{"message":"Interaction has already been acknowledged.","code":40060},"code":40060,"status":400,"method":"POST","url":"https://discord.com/api/v10/interactions/1330613003279667362/aW50ZXJhY3Rpb246MTMzMDYxMzAwMzI3OTY2NzM2Mjo2UG5YOFJSRDVDUUhvb2xWTnIxdExHcVRBOERKOFF0bVhwQ3RUZ0FQeE5QQjV6WjJ1VWIyQnVaeEEyU0NQS2xOYzdQWk5WU0pxeVFjVDdPd0FQTWlzc3doWGhBbG5ibVVuQjRmOURmc0dqeWIyU21MMHVEVTVDQXhmSTluOWVicQ/callback?with_response=false","stack":"DiscordAPIError[40060]: Interaction has already been acknowledged.\n    at handleErrors (/usr/src/app/node_modules/.pnpm/@discordjs+rest@2.4.2/node_modules/@discordjs/rest/dist/index.js:727:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async BurstHandler.runRequest (/usr/src/app/node_modules/.pnpm/@discordjs+rest@2.4.2/node_modules/@discordjs/rest/dist/index.js:831:23)\n    at async _REST.request (/usr/src/app/node_modules/.pnpm/@discordjs+rest@2.4.2/node_modules/@discordjs/rest/dist/index.js:1272:22)\n    at async ChatInputCommandInteraction.reply (/usr/src/app/node_modules/.pnpm/discord.js@14.17.3/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:194:22)\n    at async handleReply (file:///usr/src/app/src/utils/interactionHelper.js:9:13)\n    at async RecordCommand.execute (file:///usr/src/app/src/commands/audio/RecordCommand.js:63:13)\n    at async CommandRegistry.handleCommand (file:///usr/src/app/src/commands/audio/CommandRegistry.js:65:13)\n    at async Bot.handleInteraction (file:///usr/src/app/src/bot.js:77:13)"}
2025-01-19T19:01:01.998Z [31merror[39m: Discord client error: Interaction has already been acknowledged.{"requestBody":{"files":[],"json":{"type":4,"data":{"content":"❌ Failed to start recording. Please try again.","tts":false,"enforce_nonce":false}}},"rawError":{"message":"Interaction has already been acknowledged.","code":40060},"code":40060,"status":400,"method":"POST","url":"https://discord.com/api/v10/interactions/1330613003279667362/aW50ZXJhY3Rpb246MTMzMDYxMzAwMzI3OTY2NzM2Mjo2UG5YOFJSRDVDUUhvb2xWTnIxdExHcVRBOERKOFF0bVhwQ3RUZ0FQeE5QQjV6WjJ1VWIyQnVaeEEyU0NQS2xOYzdQWk5WU0pxeVFjVDdPd0FQTWlzc3doWGhBbG5ibVVuQjRmOURmc0dqeWIyU21MMHVEVTVDQXhmSTluOWVicQ/callback?with_response=false","stack":"DiscordAPIError[40060]: Interaction has already been acknowledged.\n    at handleErrors (/usr/src/app/node_modules/.pnpm/@discordjs+rest@2.4.2/node_modules/@discordjs/rest/dist/index.js:727:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async BurstHandler.runRequest (/usr/src/app/node_modules/.pnpm/@discordjs+rest@2.4.2/node_modules/@discordjs/rest/dist/index.js:831:23)\n    at async _REST.request (/usr/src/app/node_modules/.pnpm/@discordjs+rest@2.4.2/node_modules/@discordjs/rest/dist/index.js:1272:22)\n    at async ChatInputCommandInteraction.reply (/usr/src/app/node_modules/.pnpm/discord.js@14.17.3/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:194:22)\n    at async handleReply (file:///usr/src/app/src/utils/interactionHelper.js:9:13)\n    at async RecordCommand.execute (file:///usr/src/app/src/commands/audio/RecordCommand.js:63:13)\n    at async CommandRegistry.handleCommand (file:///usr/src/app/src/commands/audio/CommandRegistry.js:65:13)\n    at async Bot.handleInteraction (file:///usr/src/app/src/bot.js:77:13)"}
2025-01-19T19:04:34.056Z [31merror[39m: Error executing command record: Interaction has already been acknowledged.{"requestBody":{"files":[],"json":{"type":4,"data":{"content":"❌ Failed to start recording. Please try again.","tts":false,"enforce_nonce":false,"flags":64}}},"rawError":{"message":"Interaction has already been acknowledged.","code":40060},"code":40060,"status":400,"method":"POST","url":"https://discord.com/api/v10/interactions/1330613892950397058/aW50ZXJhY3Rpb246MTMzMDYxMzg5Mjk1MDM5NzA1ODpicmpXOEdYQmJRN0NOUGpuU0dBNW1aVG9sTzR5RVlJQ2xrdUd6andzRkVwTFdnME11Q3plNTVJdm9nOU5ST2RoUG1wSWpXTkRROXlPYnZoZURUV2E1ZXh2Q1g3YWpNMHE3cFFDTU13WjFob1pja2RnWUtJbEVOS29nN0tqcFJEYw/callback?with_response=false","stack":"DiscordAPIError[40060]: Interaction has already been acknowledged.\n    at handleErrors (/usr/src/app/node_modules/.pnpm/@discordjs+rest@2.4.2/node_modules/@discordjs/rest/dist/index.js:727:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async BurstHandler.runRequest (/usr/src/app/node_modules/.pnpm/@discordjs+rest@2.4.2/node_modules/@discordjs/rest/dist/index.js:831:23)\n    at async _REST.request (/usr/src/app/node_modules/.pnpm/@discordjs+rest@2.4.2/node_modules/@discordjs/rest/dist/index.js:1272:22)\n    at async ChatInputCommandInteraction.reply (/usr/src/app/node_modules/.pnpm/discord.js@14.17.3/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:194:22)\n    at async handleReply (file:///usr/src/app/src/utils/interactionHelper.js:6:13)\n    at async RecordCommand.execute (file:///usr/src/app/src/commands/audio/RecordCommand.js:57:13)\n    at async CommandRegistry.handleCommand (file:///usr/src/app/src/commands/audio/CommandRegistry.js:65:13)\n    at async Bot.handleInteraction (file:///usr/src/app/src/bot.js:77:13)"}
2025-01-19T19:04:34.058Z [31merror[39m: Error handling command: Interaction has already been acknowledged.{"requestBody":{"files":[],"json":{"type":4,"data":{"content":"❌ Failed to start recording. Please try again.","tts":false,"enforce_nonce":false,"flags":64}}},"rawError":{"message":"Interaction has already been acknowledged.","code":40060},"code":40060,"status":400,"method":"POST","url":"https://discord.com/api/v10/interactions/1330613892950397058/aW50ZXJhY3Rpb246MTMzMDYxMzg5Mjk1MDM5NzA1ODpicmpXOEdYQmJRN0NOUGpuU0dBNW1aVG9sTzR5RVlJQ2xrdUd6andzRkVwTFdnME11Q3plNTVJdm9nOU5ST2RoUG1wSWpXTkRROXlPYnZoZURUV2E1ZXh2Q1g3YWpNMHE3cFFDTU13WjFob1pja2RnWUtJbEVOS29nN0tqcFJEYw/callback?with_response=false","stack":"DiscordAPIError[40060]: Interaction has already been acknowledged.\n    at handleErrors (/usr/src/app/node_modules/.pnpm/@discordjs+rest@2.4.2/node_modules/@discordjs/rest/dist/index.js:727:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async BurstHandler.runRequest (/usr/src/app/node_modules/.pnpm/@discordjs+rest@2.4.2/node_modules/@discordjs/rest/dist/index.js:831:23)\n    at async _REST.request (/usr/src/app/node_modules/.pnpm/@discordjs+rest@2.4.2/node_modules/@discordjs/rest/dist/index.js:1272:22)\n    at async ChatInputCommandInteraction.reply (/usr/src/app/node_modules/.pnpm/discord.js@14.17.3/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:194:22)\n    at async handleReply (file:///usr/src/app/src/utils/interactionHelper.js:6:13)\n    at async RecordCommand.execute (file:///usr/src/app/src/commands/audio/RecordCommand.js:57:13)\n    at async CommandRegistry.handleCommand (file:///usr/src/app/src/commands/audio/CommandRegistry.js:65:13)\n    at async Bot.handleInteraction (file:///usr/src/app/src/bot.js:77:13)"}
2025-01-19T19:04:34.060Z [31merror[39m: Discord client error: Interaction has already been acknowledged.{"requestBody":{"files":[],"json":{"type":4,"data":{"content":"❌ Failed to start recording. Please try again.","tts":false,"enforce_nonce":false,"flags":64}}},"rawError":{"message":"Interaction has already been acknowledged.","code":40060},"code":40060,"status":400,"method":"POST","url":"https://discord.com/api/v10/interactions/1330613892950397058/aW50ZXJhY3Rpb246MTMzMDYxMzg5Mjk1MDM5NzA1ODpicmpXOEdYQmJRN0NOUGpuU0dBNW1aVG9sTzR5RVlJQ2xrdUd6andzRkVwTFdnME11Q3plNTVJdm9nOU5ST2RoUG1wSWpXTkRROXlPYnZoZURUV2E1ZXh2Q1g3YWpNMHE3cFFDTU13WjFob1pja2RnWUtJbEVOS29nN0tqcFJEYw/callback?with_response=false","stack":"DiscordAPIError[40060]: Interaction has already been acknowledged.\n    at handleErrors (/usr/src/app/node_modules/.pnpm/@discordjs+rest@2.4.2/node_modules/@discordjs/rest/dist/index.js:727:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async BurstHandler.runRequest (/usr/src/app/node_modules/.pnpm/@discordjs+rest@2.4.2/node_modules/@discordjs/rest/dist/index.js:831:23)\n    at async _REST.request (/usr/src/app/node_modules/.pnpm/@discordjs+rest@2.4.2/node_modules/@discordjs/rest/dist/index.js:1272:22)\n    at async ChatInputCommandInteraction.reply (/usr/src/app/node_modules/.pnpm/discord.js@14.17.3/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:194:22)\n    at async handleReply (file:///usr/src/app/src/utils/interactionHelper.js:6:13)\n    at async RecordCommand.execute (file:///usr/src/app/src/commands/audio/RecordCommand.js:57:13)\n    at async CommandRegistry.handleCommand (file:///usr/src/app/src/commands/audio/CommandRegistry.js:65:13)\n    at async Bot.handleInteraction (file:///usr/src/app/src/bot.js:77:13)"}
2025-01-19T19:04:53.516Z [31merror[39m: Error executing command stop: Interaction has already been acknowledged.{"requestBody":{"files":[],"json":{"type":4,"data":{"content":"❌ Failed to stop recording. Please try again.","tts":false,"enforce_nonce":false,"flags":64}}},"rawError":{"message":"Interaction has already been acknowledged.","code":40060},"code":40060,"status":400,"method":"POST","url":"https://discord.com/api/v10/interactions/1330613974990983298/aW50ZXJhY3Rpb246MTMzMDYxMzk3NDk5MDk4MzI5ODpEU204RkFDdHF3aUlXNFI3MnRKb0lSYnhZc1lNVFJONHF6M0NkdkI0bEQycHdUU3U5OHdiekl1SGJXV3lDQ0FUZmJZSU5oVWlDM0p5c2pmTGxFdUZhQmI5d2RuQWY3ekxDWGVaVDh4ekN4MmhKRzNsMjhrQ3VXSU05bHd0R2d6WQ/callback?with_response=false","stack":"DiscordAPIError[40060]: Interaction has already been acknowledged.\n    at handleErrors (/usr/src/app/node_modules/.pnpm/@discordjs+rest@2.4.2/node_modules/@discordjs/rest/dist/index.js:727:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async BurstHandler.runRequest (/usr/src/app/node_modules/.pnpm/@discordjs+rest@2.4.2/node_modules/@discordjs/rest/dist/index.js:831:23)\n    at async _REST.request (/usr/src/app/node_modules/.pnpm/@discordjs+rest@2.4.2/node_modules/@discordjs/rest/dist/index.js:1272:22)\n    at async ChatInputCommandInteraction.reply (/usr/src/app/node_modules/.pnpm/discord.js@14.17.3/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:194:22)\n    at async handleReply (file:///usr/src/app/src/utils/interactionHelper.js:6:13)\n    at async StopCommand.execute (file:///usr/src/app/src/commands/audio/StopCommand.js:40:13)\n    at async CommandRegistry.handleCommand (file:///usr/src/app/src/commands/audio/CommandRegistry.js:65:13)\n    at async Bot.handleInteraction (file:///usr/src/app/src/bot.js:77:13)"}
2025-01-19T19:04:53.519Z [31merror[39m: Error handling command: Interaction has already been acknowledged.{"requestBody":{"files":[],"json":{"type":4,"data":{"content":"❌ Failed to stop recording. Please try again.","tts":false,"enforce_nonce":false,"flags":64}}},"rawError":{"message":"Interaction has already been acknowledged.","code":40060},"code":40060,"status":400,"method":"POST","url":"https://discord.com/api/v10/interactions/1330613974990983298/aW50ZXJhY3Rpb246MTMzMDYxMzk3NDk5MDk4MzI5ODpEU204RkFDdHF3aUlXNFI3MnRKb0lSYnhZc1lNVFJONHF6M0NkdkI0bEQycHdUU3U5OHdiekl1SGJXV3lDQ0FUZmJZSU5oVWlDM0p5c2pmTGxFdUZhQmI5d2RuQWY3ekxDWGVaVDh4ekN4MmhKRzNsMjhrQ3VXSU05bHd0R2d6WQ/callback?with_response=false","stack":"DiscordAPIError[40060]: Interaction has already been acknowledged.\n    at handleErrors (/usr/src/app/node_modules/.pnpm/@discordjs+rest@2.4.2/node_modules/@discordjs/rest/dist/index.js:727:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async BurstHandler.runRequest (/usr/src/app/node_modules/.pnpm/@discordjs+rest@2.4.2/node_modules/@discordjs/rest/dist/index.js:831:23)\n    at async _REST.request (/usr/src/app/node_modules/.pnpm/@discordjs+rest@2.4.2/node_modules/@discordjs/rest/dist/index.js:1272:22)\n    at async ChatInputCommandInteraction.reply (/usr/src/app/node_modules/.pnpm/discord.js@14.17.3/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:194:22)\n    at async handleReply (file:///usr/src/app/src/utils/interactionHelper.js:6:13)\n    at async StopCommand.execute (file:///usr/src/app/src/commands/audio/StopCommand.js:40:13)\n    at async CommandRegistry.handleCommand (file:///usr/src/app/src/commands/audio/CommandRegistry.js:65:13)\n    at async Bot.handleInteraction (file:///usr/src/app/src/bot.js:77:13)"}
2025-01-19T19:04:53.522Z [31merror[39m: Discord client error: Interaction has already been acknowledged.{"requestBody":{"files":[],"json":{"type":4,"data":{"content":"❌ Failed to stop recording. Please try again.","tts":false,"enforce_nonce":false,"flags":64}}},"rawError":{"message":"Interaction has already been acknowledged.","code":40060},"code":40060,"status":400,"method":"POST","url":"https://discord.com/api/v10/interactions/1330613974990983298/aW50ZXJhY3Rpb246MTMzMDYxMzk3NDk5MDk4MzI5ODpEU204RkFDdHF3aUlXNFI3MnRKb0lSYnhZc1lNVFJONHF6M0NkdkI0bEQycHdUU3U5OHdiekl1SGJXV3lDQ0FUZmJZSU5oVWlDM0p5c2pmTGxFdUZhQmI5d2RuQWY3ekxDWGVaVDh4ekN4MmhKRzNsMjhrQ3VXSU05bHd0R2d6WQ/callback?with_response=false","stack":"DiscordAPIError[40060]: Interaction has already been acknowledged.\n    at handleErrors (/usr/src/app/node_modules/.pnpm/@discordjs+rest@2.4.2/node_modules/@discordjs/rest/dist/index.js:727:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async BurstHandler.runRequest (/usr/src/app/node_modules/.pnpm/@discordjs+rest@2.4.2/node_modules/@discordjs/rest/dist/index.js:831:23)\n    at async _REST.request (/usr/src/app/node_modules/.pnpm/@discordjs+rest@2.4.2/node_modules/@discordjs/rest/dist/index.js:1272:22)\n    at async ChatInputCommandInteraction.reply (/usr/src/app/node_modules/.pnpm/discord.js@14.17.3/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:194:22)\n    at async handleReply (file:///usr/src/app/src/utils/interactionHelper.js:6:13)\n    at async StopCommand.execute (file:///usr/src/app/src/commands/audio/StopCommand.js:40:13)\n    at async CommandRegistry.handleCommand (file:///usr/src/app/src/commands/audio/CommandRegistry.js:65:13)\n    at async Bot.handleInteraction (file:///usr/src/app/src/bot.js:77:13)"}
2025-01-19T19:10:01.100Z [31merror[39m: [TranscriptionService] Summary generation failed:{"location":"TranscriptionService.generateSummary","error":{"name":"Error","message":"Failed to generate summary","stack":"Error: Failed to generate summary\n    at TranscriptionService.generateSummary (file:///usr/src/app/src/services/TranscriptionService.js:104:31)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async VoiceRecorder.processRotatedRecording (file:///usr/src/app/src/VoiceRecorder.js:116:27)"},"context":{"transcriptLength":684,"transcriptSample":"This is the most interesting thing on television right now. WAAA BAAA BAAAAA WAAA BAAA BAAAAA WAAA B"}}
2025-01-19T19:10:14.964Z [31merror[39m: [TranscriptionService] Summary generation failed:{"location":"TranscriptionService.generateSummary","error":{"name":"Error","message":"Failed to generate summary","stack":"Error: Failed to generate summary\n    at TranscriptionService.generateSummary (file:///usr/src/app/src/services/TranscriptionService.js:104:31)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async file:///usr/src/app/src/services/SummaryJobService.js:24:33\n    at async Queue.<anonymous> (file:///usr/src/app/src/services/JobService.js:44:24)"},"context":{"transcriptLength":684,"transcriptSample":"This is the most interesting thing on television right now. WAAA BAAA BAAAAA WAAA BAAA BAAAAA WAAA B"}}
2025-01-19T19:10:14.964Z [31merror[39m: [SummaryJobService] Failed to generate background summary:{"error":"Failed to generate summary: Failed to generate summary","stack":"Error: Failed to generate summary: Failed to generate summary\n    at TranscriptionService.generateSummary (file:///usr/src/app/src/services/TranscriptionService.js:150:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async file:///usr/src/app/src/services/SummaryJobService.js:24:33\n    at async Queue.<anonymous> (file:///usr/src/app/src/services/JobService.js:44:24)","guildId":"1315144523336122469"}
2025-01-19T19:10:14.964Z [31merror[39m: [JobService] Error processing job in queue summary-generation:{"jobId":"2","error":"Failed to generate summary: Failed to generate summary","stack":"Error: Failed to generate summary: Failed to generate summary\n    at TranscriptionService.generateSummary (file:///usr/src/app/src/services/TranscriptionService.js:150:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async file:///usr/src/app/src/services/SummaryJobService.js:24:33\n    at async Queue.<anonymous> (file:///usr/src/app/src/services/JobService.js:44:24)"}
2025-01-19T19:10:14.975Z [31merror[39m: [JobService] Job failed in queue summary-generation:{"jobId":"2","error":"Failed to generate summary: Failed to generate summary","stack":"Error: Failed to generate summary: Failed to generate summary\n    at TranscriptionService.generateSummary (file:///usr/src/app/src/services/TranscriptionService.js:150:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async file:///usr/src/app/src/services/SummaryJobService.js:24:33\n    at async Queue.<anonymous> (file:///usr/src/app/src/services/JobService.js:44:24)","attempts":1}
2025-01-19T19:10:29.881Z [31merror[39m: [TranscriptionService] Summary generation failed:{"location":"TranscriptionService.generateSummary","error":{"name":"Error","message":"Failed to generate summary","stack":"Error: Failed to generate summary\n    at TranscriptionService.generateSummary (file:///usr/src/app/src/services/TranscriptionService.js:104:31)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async file:///usr/src/app/src/services/SummaryJobService.js:24:33\n    at async Queue.<anonymous> (file:///usr/src/app/src/services/JobService.js:44:24)"},"context":{"transcriptLength":684,"transcriptSample":"This is the most interesting thing on television right now. WAAA BAAA BAAAAA WAAA BAAA BAAAAA WAAA B"}}
2025-01-19T19:10:29.882Z [31merror[39m: [SummaryJobService] Failed to generate background summary:{"error":"Failed to generate summary: Failed to generate summary","stack":"Error: Failed to generate summary: Failed to generate summary\n    at TranscriptionService.generateSummary (file:///usr/src/app/src/services/TranscriptionService.js:150:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async file:///usr/src/app/src/services/SummaryJobService.js:24:33\n    at async Queue.<anonymous> (file:///usr/src/app/src/services/JobService.js:44:24)","guildId":"1315144523336122469"}
2025-01-19T19:10:29.882Z [31merror[39m: [JobService] Error processing job in queue summary-generation:{"jobId":"2","error":"Failed to generate summary: Failed to generate summary","stack":"Error: Failed to generate summary: Failed to generate summary\n    at TranscriptionService.generateSummary (file:///usr/src/app/src/services/TranscriptionService.js:150:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async file:///usr/src/app/src/services/SummaryJobService.js:24:33\n    at async Queue.<anonymous> (file:///usr/src/app/src/services/JobService.js:44:24)"}
2025-01-19T19:10:29.887Z [31merror[39m: [JobService] Job failed in queue summary-generation:{"jobId":"2","error":"Failed to generate summary: Failed to generate summary","stack":"Error: Failed to generate summary: Failed to generate summary\n    at TranscriptionService.generateSummary (file:///usr/src/app/src/services/TranscriptionService.js:150:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async file:///usr/src/app/src/services/SummaryJobService.js:24:33\n    at async Queue.<anonymous> (file:///usr/src/app/src/services/JobService.js:44:24)","attempts":2}
2025-01-19T19:10:46.752Z [31merror[39m: [TranscriptionService] Summary generation failed:{"location":"TranscriptionService.generateSummary","error":{"name":"Error","message":"Failed to generate summary","stack":"Error: Failed to generate summary\n    at TranscriptionService.generateSummary (file:///usr/src/app/src/services/TranscriptionService.js:104:31)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async file:///usr/src/app/src/services/SummaryJobService.js:24:33\n    at async Queue.<anonymous> (file:///usr/src/app/src/services/JobService.js:44:24)"},"context":{"transcriptLength":684,"transcriptSample":"This is the most interesting thing on television right now. WAAA BAAA BAAAAA WAAA BAAA BAAAAA WAAA B"}}
2025-01-19T19:10:46.753Z [31merror[39m: [SummaryJobService] Failed to generate background summary:{"error":"Failed to generate summary: Failed to generate summary","stack":"Error: Failed to generate summary: Failed to generate summary\n    at TranscriptionService.generateSummary (file:///usr/src/app/src/services/TranscriptionService.js:150:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async file:///usr/src/app/src/services/SummaryJobService.js:24:33\n    at async Queue.<anonymous> (file:///usr/src/app/src/services/JobService.js:44:24)","guildId":"1315144523336122469"}
2025-01-19T19:10:46.753Z [31merror[39m: [JobService] Error processing job in queue summary-generation:{"jobId":"2","error":"Failed to generate summary: Failed to generate summary","stack":"Error: Failed to generate summary: Failed to generate summary\n    at TranscriptionService.generateSummary (file:///usr/src/app/src/services/TranscriptionService.js:150:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async file:///usr/src/app/src/services/SummaryJobService.js:24:33\n    at async Queue.<anonymous> (file:///usr/src/app/src/services/JobService.js:44:24)"}
2025-01-19T19:10:46.759Z [31merror[39m: [JobService] Job failed in queue summary-generation:{"jobId":"2","error":"Failed to generate summary: Failed to generate summary","stack":"Error: Failed to generate summary: Failed to generate summary\n    at TranscriptionService.generateSummary (file:///usr/src/app/src/services/TranscriptionService.js:150:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async file:///usr/src/app/src/services/SummaryJobService.js:24:33\n    at async Queue.<anonymous> (file:///usr/src/app/src/services/JobService.js:44:24)","attempts":3}
2025-01-19T19:11:53.820Z [31merror[39m: [TranscriptionService] Summary generation failed:{"location":"TranscriptionService.generateSummary","error":{"name":"Error","message":"Failed to generate summary","stack":"Error: Failed to generate summary\n    at TranscriptionService.generateSummary (file:///usr/src/app/src/services/TranscriptionService.js:104:31)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async VoiceRecorder.processRotatedRecording (file:///usr/src/app/src/VoiceRecorder.js:116:27)"},"context":{"transcriptLength":621,"transcriptSample":"That's the way daddy likes it, that's the way daddy likes it Getting that let's not do anything toda"}}
2025-01-19T19:12:10.029Z [31merror[39m: [TranscriptionService] Summary generation failed:{"location":"TranscriptionService.generateSummary","error":{"name":"Error","message":"Failed to generate summary","stack":"Error: Failed to generate summary\n    at TranscriptionService.generateSummary (file:///usr/src/app/src/services/TranscriptionService.js:104:31)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async file:///usr/src/app/src/services/SummaryJobService.js:24:33\n    at async Queue.<anonymous> (file:///usr/src/app/src/services/JobService.js:44:24)"},"context":{"transcriptLength":621,"transcriptSample":"That's the way daddy likes it, that's the way daddy likes it Getting that let's not do anything toda"}}
2025-01-19T19:12:10.033Z [31merror[39m: [SummaryJobService] Failed to generate background summary:{"error":"Failed to generate summary: Failed to generate summary","stack":"Error: Failed to generate summary: Failed to generate summary\n    at TranscriptionService.generateSummary (file:///usr/src/app/src/services/TranscriptionService.js:150:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async file:///usr/src/app/src/services/SummaryJobService.js:24:33\n    at async Queue.<anonymous> (file:///usr/src/app/src/services/JobService.js:44:24)","guildId":"1315144523336122469"}
2025-01-19T19:12:10.033Z [31merror[39m: [JobService] Error processing job in queue summary-generation:{"jobId":"3","error":"Failed to generate summary: Failed to generate summary","stack":"Error: Failed to generate summary: Failed to generate summary\n    at TranscriptionService.generateSummary (file:///usr/src/app/src/services/TranscriptionService.js:150:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async file:///usr/src/app/src/services/SummaryJobService.js:24:33\n    at async Queue.<anonymous> (file:///usr/src/app/src/services/JobService.js:44:24)"}
2025-01-19T19:12:10.038Z [31merror[39m: [JobService] Job failed in queue summary-generation:{"jobId":"3","error":"Failed to generate summary: Failed to generate summary","stack":"Error: Failed to generate summary: Failed to generate summary\n    at TranscriptionService.generateSummary (file:///usr/src/app/src/services/TranscriptionService.js:150:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async file:///usr/src/app/src/services/SummaryJobService.js:24:33\n    at async Queue.<anonymous> (file:///usr/src/app/src/services/JobService.js:44:24)","attempts":1}
2025-01-19T19:12:24.968Z [31merror[39m: [TranscriptionService] Summary generation failed:{"location":"TranscriptionService.generateSummary","error":{"name":"Error","message":"Failed to generate summary","stack":"Error: Failed to generate summary\n    at TranscriptionService.generateSummary (file:///usr/src/app/src/services/TranscriptionService.js:104:31)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async file:///usr/src/app/src/services/SummaryJobService.js:24:33\n    at async Queue.<anonymous> (file:///usr/src/app/src/services/JobService.js:44:24)"},"context":{"transcriptLength":621,"transcriptSample":"That's the way daddy likes it, that's the way daddy likes it Getting that let's not do anything toda"}}
2025-01-19T19:12:24.969Z [31merror[39m: [SummaryJobService] Failed to generate background summary:{"error":"Failed to generate summary: Failed to generate summary","stack":"Error: Failed to generate summary: Failed to generate summary\n    at TranscriptionService.generateSummary (file:///usr/src/app/src/services/TranscriptionService.js:150:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async file:///usr/src/app/src/services/SummaryJobService.js:24:33\n    at async Queue.<anonymous> (file:///usr/src/app/src/services/JobService.js:44:24)","guildId":"1315144523336122469"}
2025-01-19T19:12:24.970Z [31merror[39m: [JobService] Error processing job in queue summary-generation:{"jobId":"3","error":"Failed to generate summary: Failed to generate summary","stack":"Error: Failed to generate summary: Failed to generate summary\n    at TranscriptionService.generateSummary (file:///usr/src/app/src/services/TranscriptionService.js:150:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async file:///usr/src/app/src/services/SummaryJobService.js:24:33\n    at async Queue.<anonymous> (file:///usr/src/app/src/services/JobService.js:44:24)"}
2025-01-19T19:12:24.974Z [31merror[39m: [JobService] Job failed in queue summary-generation:{"jobId":"3","error":"Failed to generate summary: Failed to generate summary","stack":"Error: Failed to generate summary: Failed to generate summary\n    at TranscriptionService.generateSummary (file:///usr/src/app/src/services/TranscriptionService.js:150:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async file:///usr/src/app/src/services/SummaryJobService.js:24:33\n    at async Queue.<anonymous> (file:///usr/src/app/src/services/JobService.js:44:24)","attempts":2}
2025-01-19T19:20:14.987Z [31merror[39m: Error executing command record: Interaction has already been acknowledged.{"requestBody":{"files":[],"json":{"type":4,"data":{"content":"❌ Failed to start recording. Please try again.","tts":false,"enforce_nonce":false,"flags":64}}},"rawError":{"message":"Interaction has already been acknowledged.","code":40060},"code":40060,"status":400,"method":"POST","url":"https://discord.com/api/v10/interactions/1330617839362506882/aW50ZXJhY3Rpb246MTMzMDYxNzgzOTM2MjUwNjg4MjpKRTM1b3BGbzBHTU9mSWFDbGlNaEk2SThFaGhQOTRwTHBCbmhZWjRtUTlseXcwY1BxbGpiZ3dNMEZLRGhwRHJuMXY5UnlsbWt0VDlsM25wQkZ1TlM0eXI5Z1lqdHh0T09pQUFsa1hHTFI5eGt2WlZFVUNlVXZqUGtMSk5RZ2pkNg/callback?with_response=false","stack":"DiscordAPIError[40060]: Interaction has already been acknowledged.\n    at handleErrors (/usr/src/app/node_modules/.pnpm/@discordjs+rest@2.4.2/node_modules/@discordjs/rest/dist/index.js:727:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async BurstHandler.runRequest (/usr/src/app/node_modules/.pnpm/@discordjs+rest@2.4.2/node_modules/@discordjs/rest/dist/index.js:831:23)\n    at async _REST.request (/usr/src/app/node_modules/.pnpm/@discordjs+rest@2.4.2/node_modules/@discordjs/rest/dist/index.js:1272:22)\n    at async ChatInputCommandInteraction.reply (/usr/src/app/node_modules/.pnpm/discord.js@14.17.3/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:194:22)\n    at async handleReply (file:///usr/src/app/src/utils/interactionHelper.js:6:13)\n    at async RecordCommand.execute (file:///usr/src/app/src/commands/audio/RecordCommand.js:57:13)\n    at async CommandRegistry.handleCommand (file:///usr/src/app/src/commands/audio/CommandRegistry.js:65:13)\n    at async Bot.handleInteraction (file:///usr/src/app/src/bot.js:77:13)"}
2025-01-19T19:20:14.989Z [31merror[39m: Error handling command: Interaction has already been acknowledged.{"requestBody":{"files":[],"json":{"type":4,"data":{"content":"❌ Failed to start recording. Please try again.","tts":false,"enforce_nonce":false,"flags":64}}},"rawError":{"message":"Interaction has already been acknowledged.","code":40060},"code":40060,"status":400,"method":"POST","url":"https://discord.com/api/v10/interactions/1330617839362506882/aW50ZXJhY3Rpb246MTMzMDYxNzgzOTM2MjUwNjg4MjpKRTM1b3BGbzBHTU9mSWFDbGlNaEk2SThFaGhQOTRwTHBCbmhZWjRtUTlseXcwY1BxbGpiZ3dNMEZLRGhwRHJuMXY5UnlsbWt0VDlsM25wQkZ1TlM0eXI5Z1lqdHh0T09pQUFsa1hHTFI5eGt2WlZFVUNlVXZqUGtMSk5RZ2pkNg/callback?with_response=false","stack":"DiscordAPIError[40060]: Interaction has already been acknowledged.\n    at handleErrors (/usr/src/app/node_modules/.pnpm/@discordjs+rest@2.4.2/node_modules/@discordjs/rest/dist/index.js:727:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async BurstHandler.runRequest (/usr/src/app/node_modules/.pnpm/@discordjs+rest@2.4.2/node_modules/@discordjs/rest/dist/index.js:831:23)\n    at async _REST.request (/usr/src/app/node_modules/.pnpm/@discordjs+rest@2.4.2/node_modules/@discordjs/rest/dist/index.js:1272:22)\n    at async ChatInputCommandInteraction.reply (/usr/src/app/node_modules/.pnpm/discord.js@14.17.3/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:194:22)\n    at async handleReply (file:///usr/src/app/src/utils/interactionHelper.js:6:13)\n    at async RecordCommand.execute (file:///usr/src/app/src/commands/audio/RecordCommand.js:57:13)\n    at async CommandRegistry.handleCommand (file:///usr/src/app/src/commands/audio/CommandRegistry.js:65:13)\n    at async Bot.handleInteraction (file:///usr/src/app/src/bot.js:77:13)"}
2025-01-19T19:20:14.990Z [31merror[39m: Discord client error: Interaction has already been acknowledged.{"requestBody":{"files":[],"json":{"type":4,"data":{"content":"❌ Failed to start recording. Please try again.","tts":false,"enforce_nonce":false,"flags":64}}},"rawError":{"message":"Interaction has already been acknowledged.","code":40060},"code":40060,"status":400,"method":"POST","url":"https://discord.com/api/v10/interactions/1330617839362506882/aW50ZXJhY3Rpb246MTMzMDYxNzgzOTM2MjUwNjg4MjpKRTM1b3BGbzBHTU9mSWFDbGlNaEk2SThFaGhQOTRwTHBCbmhZWjRtUTlseXcwY1BxbGpiZ3dNMEZLRGhwRHJuMXY5UnlsbWt0VDlsM25wQkZ1TlM0eXI5Z1lqdHh0T09pQUFsa1hHTFI5eGt2WlZFVUNlVXZqUGtMSk5RZ2pkNg/callback?with_response=false","stack":"DiscordAPIError[40060]: Interaction has already been acknowledged.\n    at handleErrors (/usr/src/app/node_modules/.pnpm/@discordjs+rest@2.4.2/node_modules/@discordjs/rest/dist/index.js:727:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async BurstHandler.runRequest (/usr/src/app/node_modules/.pnpm/@discordjs+rest@2.4.2/node_modules/@discordjs/rest/dist/index.js:831:23)\n    at async _REST.request (/usr/src/app/node_modules/.pnpm/@discordjs+rest@2.4.2/node_modules/@discordjs/rest/dist/index.js:1272:22)\n    at async ChatInputCommandInteraction.reply (/usr/src/app/node_modules/.pnpm/discord.js@14.17.3/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:194:22)\n    at async handleReply (file:///usr/src/app/src/utils/interactionHelper.js:6:13)\n    at async RecordCommand.execute (file:///usr/src/app/src/commands/audio/RecordCommand.js:57:13)\n    at async CommandRegistry.handleCommand (file:///usr/src/app/src/commands/audio/CommandRegistry.js:65:13)\n    at async Bot.handleInteraction (file:///usr/src/app/src/bot.js:77:13)"}
2025-01-19T19:24:44.033Z [31merror[39m: [TranscriptionService] Summary generation failed:{"location":"TranscriptionService.generateSummary","error":{"name":"Error","message":"Failed to generate summary","stack":"Error: Failed to generate summary\n    at TranscriptionService.generateSummary (file:///usr/src/app/src/services/TranscriptionService.js:104:31)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async VoiceRecorder.processRotatedRecording (file:///usr/src/app/src/VoiceRecorder.js:116:27)"},"context":{"transcriptLength":1297,"transcriptSample":"What do you mean, it's dawning on you? It's just cold, you know? This is- this is dumb. You have thi"}}
2025-01-19T19:28:38.870Z [31merror[39m: [TranscriptionService] Summary generation failed:{"location":"TranscriptionService.generateSummary","error":{"name":"Error","message":"Failed to generate summary","stack":"Error: Failed to generate summary\n    at TranscriptionService.generateSummary (file:///usr/src/app/src/services/TranscriptionService.js:104:31)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async VoiceRecorder.processRotatedRecording (file:///usr/src/app/src/VoiceRecorder.js:116:27)"},"context":{"transcriptLength":11,"transcriptSample":"Thank you.\n"}}
2025-01-19T19:35:31.643Z [31merror[39m: [TranscriptionService] Summary generation failed:{"location":"TranscriptionService.generateSummary","error":{"name":"Error","message":"Failed to generate summary","stack":"Error: Failed to generate summary\n    at TranscriptionService.generateSummary (file:///usr/src/app/src/services/TranscriptionService.js:104:31)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async file:///usr/src/app/src/services/SummaryJobService.js:24:33\n    at async Queue.<anonymous> (file:///usr/src/app/src/services/JobService.js:44:24)"},"context":{"transcriptLength":11,"transcriptSample":"Thank you.\n"}}
2025-01-19T19:35:31.644Z [31merror[39m: [SummaryJobService] Failed to generate background summary:{"error":"Failed to generate summary: Failed to generate summary","stack":"Error: Failed to generate summary: Failed to generate summary\n    at TranscriptionService.generateSummary (file:///usr/src/app/src/services/TranscriptionService.js:150:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async file:///usr/src/app/src/services/SummaryJobService.js:24:33\n    at async Queue.<anonymous> (file:///usr/src/app/src/services/JobService.js:44:24)","guildId":"1315144523336122469"}
2025-01-19T19:40:01.273Z [31merror[39m: [VoiceRecorder] Error rotating files: filename is not defined{"stack":"ReferenceError: filename is not defined\n    at VoiceRecorder.rotateStreams (file:///usr/src/app/src/VoiceRecorder.js:57:41)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"}
2025-01-19T19:40:01.274Z [31merror[39m: [VoiceRecorder] Error rotating files: filename is not defined{"stack":"ReferenceError: filename is not defined\n    at VoiceRecorder.rotateStreams (file:///usr/src/app/src/VoiceRecorder.js:57:41)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"}
2025-01-19T19:41:42.898Z [31merror[39m: Error executing command record: Interaction has already been acknowledged.{"requestBody":{"files":[],"json":{"type":4,"data":{"content":"❌ Failed to start recording. Please try again.","tts":false,"enforce_nonce":false,"flags":64}}},"rawError":{"message":"Interaction has already been acknowledged.","code":40060},"code":40060,"status":400,"method":"POST","url":"https://discord.com/api/v10/interactions/1330623241374400603/aW50ZXJhY3Rpb246MTMzMDYyMzI0MTM3NDQwMDYwMzpXY1FyYUpVUGU0M0J4UldlR3FiSGNwQUxwZzFpV0RGNERiOG80cW1pTnJFb1N3MjRub21MM3h5Q3pHSlZBRm9RQ0tvQ0ZNc2ppYjB3czhJUzRrUlFaNVpuN0RmR2FZdnZBSE0zSWgxZ0MwSkU0VDJrVUZvbzQ0aFUyVlVNN2VlaA/callback?with_response=false","stack":"DiscordAPIError[40060]: Interaction has already been acknowledged.\n    at handleErrors (/usr/src/app/node_modules/.pnpm/@discordjs+rest@2.4.2/node_modules/@discordjs/rest/dist/index.js:727:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async BurstHandler.runRequest (/usr/src/app/node_modules/.pnpm/@discordjs+rest@2.4.2/node_modules/@discordjs/rest/dist/index.js:831:23)\n    at async _REST.request (/usr/src/app/node_modules/.pnpm/@discordjs+rest@2.4.2/node_modules/@discordjs/rest/dist/index.js:1272:22)\n    at async ChatInputCommandInteraction.reply (/usr/src/app/node_modules/.pnpm/discord.js@14.17.3/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:194:22)\n    at async handleReply (file:///usr/src/app/src/utils/interactionHelper.js:6:13)\n    at async RecordCommand.execute (file:///usr/src/app/src/commands/audio/RecordCommand.js:57:13)\n    at async CommandRegistry.handleCommand (file:///usr/src/app/src/commands/audio/CommandRegistry.js:65:13)\n    at async Bot.handleInteraction (file:///usr/src/app/src/bot.js:77:13)"}
2025-01-19T19:41:42.902Z [31merror[39m: Error handling command: Interaction has already been acknowledged.{"requestBody":{"files":[],"json":{"type":4,"data":{"content":"❌ Failed to start recording. Please try again.","tts":false,"enforce_nonce":false,"flags":64}}},"rawError":{"message":"Interaction has already been acknowledged.","code":40060},"code":40060,"status":400,"method":"POST","url":"https://discord.com/api/v10/interactions/1330623241374400603/aW50ZXJhY3Rpb246MTMzMDYyMzI0MTM3NDQwMDYwMzpXY1FyYUpVUGU0M0J4UldlR3FiSGNwQUxwZzFpV0RGNERiOG80cW1pTnJFb1N3MjRub21MM3h5Q3pHSlZBRm9RQ0tvQ0ZNc2ppYjB3czhJUzRrUlFaNVpuN0RmR2FZdnZBSE0zSWgxZ0MwSkU0VDJrVUZvbzQ0aFUyVlVNN2VlaA/callback?with_response=false","stack":"DiscordAPIError[40060]: Interaction has already been acknowledged.\n    at handleErrors (/usr/src/app/node_modules/.pnpm/@discordjs+rest@2.4.2/node_modules/@discordjs/rest/dist/index.js:727:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async BurstHandler.runRequest (/usr/src/app/node_modules/.pnpm/@discordjs+rest@2.4.2/node_modules/@discordjs/rest/dist/index.js:831:23)\n    at async _REST.request (/usr/src/app/node_modules/.pnpm/@discordjs+rest@2.4.2/node_modules/@discordjs/rest/dist/index.js:1272:22)\n    at async ChatInputCommandInteraction.reply (/usr/src/app/node_modules/.pnpm/discord.js@14.17.3/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:194:22)\n    at async handleReply (file:///usr/src/app/src/utils/interactionHelper.js:6:13)\n    at async RecordCommand.execute (file:///usr/src/app/src/commands/audio/RecordCommand.js:57:13)\n    at async CommandRegistry.handleCommand (file:///usr/src/app/src/commands/audio/CommandRegistry.js:65:13)\n    at async Bot.handleInteraction (file:///usr/src/app/src/bot.js:77:13)"}
2025-01-19T19:41:42.904Z [31merror[39m: Discord client error: Interaction has already been acknowledged.{"requestBody":{"files":[],"json":{"type":4,"data":{"content":"❌ Failed to start recording. Please try again.","tts":false,"enforce_nonce":false,"flags":64}}},"rawError":{"message":"Interaction has already been acknowledged.","code":40060},"code":40060,"status":400,"method":"POST","url":"https://discord.com/api/v10/interactions/1330623241374400603/aW50ZXJhY3Rpb246MTMzMDYyMzI0MTM3NDQwMDYwMzpXY1FyYUpVUGU0M0J4UldlR3FiSGNwQUxwZzFpV0RGNERiOG80cW1pTnJFb1N3MjRub21MM3h5Q3pHSlZBRm9RQ0tvQ0ZNc2ppYjB3czhJUzRrUlFaNVpuN0RmR2FZdnZBSE0zSWgxZ0MwSkU0VDJrVUZvbzQ0aFUyVlVNN2VlaA/callback?with_response=false","stack":"DiscordAPIError[40060]: Interaction has already been acknowledged.\n    at handleErrors (/usr/src/app/node_modules/.pnpm/@discordjs+rest@2.4.2/node_modules/@discordjs/rest/dist/index.js:727:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async BurstHandler.runRequest (/usr/src/app/node_modules/.pnpm/@discordjs+rest@2.4.2/node_modules/@discordjs/rest/dist/index.js:831:23)\n    at async _REST.request (/usr/src/app/node_modules/.pnpm/@discordjs+rest@2.4.2/node_modules/@discordjs/rest/dist/index.js:1272:22)\n    at async ChatInputCommandInteraction.reply (/usr/src/app/node_modules/.pnpm/discord.js@14.17.3/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:194:22)\n    at async handleReply (file:///usr/src/app/src/utils/interactionHelper.js:6:13)\n    at async RecordCommand.execute (file:///usr/src/app/src/commands/audio/RecordCommand.js:57:13)\n    at async CommandRegistry.handleCommand (file:///usr/src/app/src/commands/audio/CommandRegistry.js:65:13)\n    at async Bot.handleInteraction (file:///usr/src/app/src/bot.js:77:13)"}
2025-01-19T19:41:46.980Z [31merror[39m: Error executing command record: Interaction has already been acknowledged.{"requestBody":{"files":[],"json":{"type":4,"data":{"content":"❌ Failed to start recording. Please try again.","tts":false,"enforce_nonce":false,"flags":64}}},"rawError":{"message":"Interaction has already been acknowledged.","code":40060},"code":40060,"status":400,"method":"POST","url":"https://discord.com/api/v10/interactions/1330623258705264710/aW50ZXJhY3Rpb246MTMzMDYyMzI1ODcwNTI2NDcxMDpaTWxBSXJiN0xNODZWckJBRmFUV3BjRzN6ZHhEVk9HdHd0TmJCQnd3RzVBTldRdEFlT01Jb1NnMWdDUU91Z0N4WnE2d1NpSTMyRWZBazgyTXl3ekJZNGoxOGdGN0lGR0pGNDdUVUFMT2VsbVcwQklydkRyM2FhaWFkVHVyNm9jeQ/callback?with_response=false","stack":"DiscordAPIError[40060]: Interaction has already been acknowledged.\n    at handleErrors (/usr/src/app/node_modules/.pnpm/@discordjs+rest@2.4.2/node_modules/@discordjs/rest/dist/index.js:727:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async BurstHandler.runRequest (/usr/src/app/node_modules/.pnpm/@discordjs+rest@2.4.2/node_modules/@discordjs/rest/dist/index.js:831:23)\n    at async _REST.request (/usr/src/app/node_modules/.pnpm/@discordjs+rest@2.4.2/node_modules/@discordjs/rest/dist/index.js:1272:22)\n    at async ChatInputCommandInteraction.reply (/usr/src/app/node_modules/.pnpm/discord.js@14.17.3/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:194:22)\n    at async handleReply (file:///usr/src/app/src/utils/interactionHelper.js:6:13)\n    at async RecordCommand.execute (file:///usr/src/app/src/commands/audio/RecordCommand.js:57:13)\n    at async CommandRegistry.handleCommand (file:///usr/src/app/src/commands/audio/CommandRegistry.js:65:13)\n    at async Bot.handleInteraction (file:///usr/src/app/src/bot.js:77:13)"}
2025-01-19T19:41:46.983Z [31merror[39m: Error handling command: Interaction has already been acknowledged.{"requestBody":{"files":[],"json":{"type":4,"data":{"content":"❌ Failed to start recording. Please try again.","tts":false,"enforce_nonce":false,"flags":64}}},"rawError":{"message":"Interaction has already been acknowledged.","code":40060},"code":40060,"status":400,"method":"POST","url":"https://discord.com/api/v10/interactions/1330623258705264710/aW50ZXJhY3Rpb246MTMzMDYyMzI1ODcwNTI2NDcxMDpaTWxBSXJiN0xNODZWckJBRmFUV3BjRzN6ZHhEVk9HdHd0TmJCQnd3RzVBTldRdEFlT01Jb1NnMWdDUU91Z0N4WnE2d1NpSTMyRWZBazgyTXl3ekJZNGoxOGdGN0lGR0pGNDdUVUFMT2VsbVcwQklydkRyM2FhaWFkVHVyNm9jeQ/callback?with_response=false","stack":"DiscordAPIError[40060]: Interaction has already been acknowledged.\n    at handleErrors (/usr/src/app/node_modules/.pnpm/@discordjs+rest@2.4.2/node_modules/@discordjs/rest/dist/index.js:727:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async BurstHandler.runRequest (/usr/src/app/node_modules/.pnpm/@discordjs+rest@2.4.2/node_modules/@discordjs/rest/dist/index.js:831:23)\n    at async _REST.request (/usr/src/app/node_modules/.pnpm/@discordjs+rest@2.4.2/node_modules/@discordjs/rest/dist/index.js:1272:22)\n    at async ChatInputCommandInteraction.reply (/usr/src/app/node_modules/.pnpm/discord.js@14.17.3/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:194:22)\n    at async handleReply (file:///usr/src/app/src/utils/interactionHelper.js:6:13)\n    at async RecordCommand.execute (file:///usr/src/app/src/commands/audio/RecordCommand.js:57:13)\n    at async CommandRegistry.handleCommand (file:///usr/src/app/src/commands/audio/CommandRegistry.js:65:13)\n    at async Bot.handleInteraction (file:///usr/src/app/src/bot.js:77:13)"}
2025-01-19T19:41:46.983Z [31merror[39m: Discord client error: Interaction has already been acknowledged.{"requestBody":{"files":[],"json":{"type":4,"data":{"content":"❌ Failed to start recording. Please try again.","tts":false,"enforce_nonce":false,"flags":64}}},"rawError":{"message":"Interaction has already been acknowledged.","code":40060},"code":40060,"status":400,"method":"POST","url":"https://discord.com/api/v10/interactions/1330623258705264710/aW50ZXJhY3Rpb246MTMzMDYyMzI1ODcwNTI2NDcxMDpaTWxBSXJiN0xNODZWckJBRmFUV3BjRzN6ZHhEVk9HdHd0TmJCQnd3RzVBTldRdEFlT01Jb1NnMWdDUU91Z0N4WnE2d1NpSTMyRWZBazgyTXl3ekJZNGoxOGdGN0lGR0pGNDdUVUFMT2VsbVcwQklydkRyM2FhaWFkVHVyNm9jeQ/callback?with_response=false","stack":"DiscordAPIError[40060]: Interaction has already been acknowledged.\n    at handleErrors (/usr/src/app/node_modules/.pnpm/@discordjs+rest@2.4.2/node_modules/@discordjs/rest/dist/index.js:727:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async BurstHandler.runRequest (/usr/src/app/node_modules/.pnpm/@discordjs+rest@2.4.2/node_modules/@discordjs/rest/dist/index.js:831:23)\n    at async _REST.request (/usr/src/app/node_modules/.pnpm/@discordjs+rest@2.4.2/node_modules/@discordjs/rest/dist/index.js:1272:22)\n    at async ChatInputCommandInteraction.reply (/usr/src/app/node_modules/.pnpm/discord.js@14.17.3/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:194:22)\n    at async handleReply (file:///usr/src/app/src/utils/interactionHelper.js:6:13)\n    at async RecordCommand.execute (file:///usr/src/app/src/commands/audio/RecordCommand.js:57:13)\n    at async CommandRegistry.handleCommand (file:///usr/src/app/src/commands/audio/CommandRegistry.js:65:13)\n    at async Bot.handleInteraction (file:///usr/src/app/src/bot.js:77:13)"}
2025-01-19T19:41:51.998Z [31merror[39m: Error executing command stop: Interaction has already been acknowledged.{"requestBody":{"files":[],"json":{"type":4,"data":{"content":"❌ Failed to stop recording. Please try again.","tts":false,"enforce_nonce":false,"flags":64}}},"rawError":{"message":"Interaction has already been acknowledged.","code":40060},"code":40060,"status":400,"method":"POST","url":"https://discord.com/api/v10/interactions/1330623279550955550/aW50ZXJhY3Rpb246MTMzMDYyMzI3OTU1MDk1NTU1MDpEeW5EYkd6Rzhoc3p0S0ZpWjM5YUlmRWVETlZXWHp3QWE4c0xIT21JSGhkTEhGNVN4Q09JUVduT0xQcERMaWV4cFJ6UW5pNEdmVlplcnk5MWU4OGxtYU9MYnFlM2JlOE4xTGp2cFVYYWhKYWo5YUUzVEdRTzR0NlE5MkZQcUV3ZQ/callback?with_response=false","stack":"DiscordAPIError[40060]: Interaction has already been acknowledged.\n    at handleErrors (/usr/src/app/node_modules/.pnpm/@discordjs+rest@2.4.2/node_modules/@discordjs/rest/dist/index.js:727:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async BurstHandler.runRequest (/usr/src/app/node_modules/.pnpm/@discordjs+rest@2.4.2/node_modules/@discordjs/rest/dist/index.js:831:23)\n    at async _REST.request (/usr/src/app/node_modules/.pnpm/@discordjs+rest@2.4.2/node_modules/@discordjs/rest/dist/index.js:1272:22)\n    at async ChatInputCommandInteraction.reply (/usr/src/app/node_modules/.pnpm/discord.js@14.17.3/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:194:22)\n    at async handleReply (file:///usr/src/app/src/utils/interactionHelper.js:6:13)\n    at async StopCommand.execute (file:///usr/src/app/src/commands/audio/StopCommand.js:40:13)\n    at async CommandRegistry.handleCommand (file:///usr/src/app/src/commands/audio/CommandRegistry.js:65:13)\n    at async Bot.handleInteraction (file:///usr/src/app/src/bot.js:77:13)"}
2025-01-19T19:41:52.000Z [31merror[39m: Error handling command: Interaction has already been acknowledged.{"requestBody":{"files":[],"json":{"type":4,"data":{"content":"❌ Failed to stop recording. Please try again.","tts":false,"enforce_nonce":false,"flags":64}}},"rawError":{"message":"Interaction has already been acknowledged.","code":40060},"code":40060,"status":400,"method":"POST","url":"https://discord.com/api/v10/interactions/1330623279550955550/aW50ZXJhY3Rpb246MTMzMDYyMzI3OTU1MDk1NTU1MDpEeW5EYkd6Rzhoc3p0S0ZpWjM5YUlmRWVETlZXWHp3QWE4c0xIT21JSGhkTEhGNVN4Q09JUVduT0xQcERMaWV4cFJ6UW5pNEdmVlplcnk5MWU4OGxtYU9MYnFlM2JlOE4xTGp2cFVYYWhKYWo5YUUzVEdRTzR0NlE5MkZQcUV3ZQ/callback?with_response=false","stack":"DiscordAPIError[40060]: Interaction has already been acknowledged.\n    at handleErrors (/usr/src/app/node_modules/.pnpm/@discordjs+rest@2.4.2/node_modules/@discordjs/rest/dist/index.js:727:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async BurstHandler.runRequest (/usr/src/app/node_modules/.pnpm/@discordjs+rest@2.4.2/node_modules/@discordjs/rest/dist/index.js:831:23)\n    at async _REST.request (/usr/src/app/node_modules/.pnpm/@discordjs+rest@2.4.2/node_modules/@discordjs/rest/dist/index.js:1272:22)\n    at async ChatInputCommandInteraction.reply (/usr/src/app/node_modules/.pnpm/discord.js@14.17.3/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:194:22)\n    at async handleReply (file:///usr/src/app/src/utils/interactionHelper.js:6:13)\n    at async StopCommand.execute (file:///usr/src/app/src/commands/audio/StopCommand.js:40:13)\n    at async CommandRegistry.handleCommand (file:///usr/src/app/src/commands/audio/CommandRegistry.js:65:13)\n    at async Bot.handleInteraction (file:///usr/src/app/src/bot.js:77:13)"}
2025-01-19T19:41:52.002Z [31merror[39m: Discord client error: Interaction has already been acknowledged.{"requestBody":{"files":[],"json":{"type":4,"data":{"content":"❌ Failed to stop recording. Please try again.","tts":false,"enforce_nonce":false,"flags":64}}},"rawError":{"message":"Interaction has already been acknowledged.","code":40060},"code":40060,"status":400,"method":"POST","url":"https://discord.com/api/v10/interactions/1330623279550955550/aW50ZXJhY3Rpb246MTMzMDYyMzI3OTU1MDk1NTU1MDpEeW5EYkd6Rzhoc3p0S0ZpWjM5YUlmRWVETlZXWHp3QWE4c0xIT21JSGhkTEhGNVN4Q09JUVduT0xQcERMaWV4cFJ6UW5pNEdmVlplcnk5MWU4OGxtYU9MYnFlM2JlOE4xTGp2cFVYYWhKYWo5YUUzVEdRTzR0NlE5MkZQcUV3ZQ/callback?with_response=false","stack":"DiscordAPIError[40060]: Interaction has already been acknowledged.\n    at handleErrors (/usr/src/app/node_modules/.pnpm/@discordjs+rest@2.4.2/node_modules/@discordjs/rest/dist/index.js:727:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async BurstHandler.runRequest (/usr/src/app/node_modules/.pnpm/@discordjs+rest@2.4.2/node_modules/@discordjs/rest/dist/index.js:831:23)\n    at async _REST.request (/usr/src/app/node_modules/.pnpm/@discordjs+rest@2.4.2/node_modules/@discordjs/rest/dist/index.js:1272:22)\n    at async ChatInputCommandInteraction.reply (/usr/src/app/node_modules/.pnpm/discord.js@14.17.3/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:194:22)\n    at async handleReply (file:///usr/src/app/src/utils/interactionHelper.js:6:13)\n    at async StopCommand.execute (file:///usr/src/app/src/commands/audio/StopCommand.js:40:13)\n    at async CommandRegistry.handleCommand (file:///usr/src/app/src/commands/audio/CommandRegistry.js:65:13)\n    at async Bot.handleInteraction (file:///usr/src/app/src/bot.js:77:13)"}
2025-01-19T19:44:47.672Z [31merror[39m: [TranscriptionService] Summary generation failed:{"location":"TranscriptionService.generateSummary","error":{"name":"Error","message":"Failed to generate summary","stack":"Error: Failed to generate summary\n    at TranscriptionService.generateSummary (file:///usr/src/app/src/services/TranscriptionService.js:104:31)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async VoiceRecorder.processRotatedRecording (file:///usr/src/app/src/VoiceRecorder.js:109:27)"},"context":{"transcriptLength":128,"transcriptSample":"Transcribed by https://otter.ai Transcribed by https://otter.ai Transcribed by https://otter.ai Tran"}}
2025-01-19T19:45:01.482Z [31merror[39m: [TranscriptionService] Summary generation failed:{"location":"TranscriptionService.generateSummary","error":{"name":"Error","message":"Failed to generate summary","stack":"Error: Failed to generate summary\n    at TranscriptionService.generateSummary (file:///usr/src/app/src/services/TranscriptionService.js:104:31)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async file:///usr/src/app/src/services/SummaryJobService.js:24:33\n    at async Queue.<anonymous> (file:///usr/src/app/src/services/JobService.js:44:24)"},"context":{"transcriptLength":128,"transcriptSample":"Transcribed by https://otter.ai Transcribed by https://otter.ai Transcribed by https://otter.ai Tran"}}
2025-01-19T19:45:01.482Z [31merror[39m: [SummaryJobService] Failed to generate background summary:{"error":"Failed to generate summary: Failed to generate summary","stack":"Error: Failed to generate summary: Failed to generate summary\n    at TranscriptionService.generateSummary (file:///usr/src/app/src/services/TranscriptionService.js:150:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async file:///usr/src/app/src/services/SummaryJobService.js:24:33\n    at async Queue.<anonymous> (file:///usr/src/app/src/services/JobService.js:44:24)","guildId":"1315144523336122469"}
2025-01-19T19:46:48.595Z [31merror[39m: [TranscriptionService] Summary generation failed:{"location":"TranscriptionService.generateSummary","error":{"name":"Error","message":"Failed to generate summary","stack":"Error: Failed to generate summary\n    at TranscriptionService.generateSummary (file:///usr/src/app/src/services/TranscriptionService.js:104:31)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async VoiceRecorder.processRotatedRecording (file:///usr/src/app/src/VoiceRecorder.js:109:27)"},"context":{"transcriptLength":530,"transcriptSample":"Please note that the audio may not be 100% accurate. Please note that the audio may not be 100% accu"}}
2025-01-19T19:47:02.280Z [31merror[39m: [TranscriptionService] Summary generation failed:{"location":"TranscriptionService.generateSummary","error":{"name":"Error","message":"Failed to generate summary","stack":"Error: Failed to generate summary\n    at TranscriptionService.generateSummary (file:///usr/src/app/src/services/TranscriptionService.js:104:31)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async file:///usr/src/app/src/services/SummaryJobService.js:24:33\n    at async Queue.<anonymous> (file:///usr/src/app/src/services/JobService.js:44:24)"},"context":{"transcriptLength":530,"transcriptSample":"Please note that the audio may not be 100% accurate. Please note that the audio may not be 100% accu"}}
2025-01-19T19:47:02.281Z [31merror[39m: [SummaryJobService] Failed to generate background summary:{"error":"Failed to generate summary: Failed to generate summary","stack":"Error: Failed to generate summary: Failed to generate summary\n    at TranscriptionService.generateSummary (file:///usr/src/app/src/services/TranscriptionService.js:150:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async file:///usr/src/app/src/services/SummaryJobService.js:24:33\n    at async Queue.<anonymous> (file:///usr/src/app/src/services/JobService.js:44:24)","guildId":"1315144523336122469"}
2025-01-19T19:48:49.631Z [31merror[39m: [TranscriptionService] Summary generation failed:{"location":"TranscriptionService.generateSummary","error":{"name":"Error","message":"Failed to generate summary","stack":"Error: Failed to generate summary\n    at TranscriptionService.generateSummary (file:///usr/src/app/src/services/TranscriptionService.js:104:31)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async VoiceRecorder.processRotatedRecording (file:///usr/src/app/src/VoiceRecorder.js:109:27)"},"context":{"transcriptLength":695,"transcriptSample":"No idea, I'm his friend's dad. I'm over here. Yeah, it's my friend's father. How does your friend's "}}
2025-01-19T19:49:03.300Z [31merror[39m: [TranscriptionService] Summary generation failed:{"location":"TranscriptionService.generateSummary","error":{"name":"Error","message":"Failed to generate summary","stack":"Error: Failed to generate summary\n    at TranscriptionService.generateSummary (file:///usr/src/app/src/services/TranscriptionService.js:104:31)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async file:///usr/src/app/src/services/SummaryJobService.js:24:33\n    at async Queue.<anonymous> (file:///usr/src/app/src/services/JobService.js:44:24)"},"context":{"transcriptLength":695,"transcriptSample":"No idea, I'm his friend's dad. I'm over here. Yeah, it's my friend's father. How does your friend's "}}
2025-01-19T19:49:03.300Z [31merror[39m: [SummaryJobService] Failed to generate background summary:{"error":"Failed to generate summary: Failed to generate summary","stack":"Error: Failed to generate summary: Failed to generate summary\n    at TranscriptionService.generateSummary (file:///usr/src/app/src/services/TranscriptionService.js:150:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async file:///usr/src/app/src/services/SummaryJobService.js:24:33\n    at async Queue.<anonymous> (file:///usr/src/app/src/services/JobService.js:44:24)","guildId":"1315144523336122469"}
2025-01-19T19:52:31.412Z [31merror[39m: [TranscriptionService] Transcription failed: 400 Audio file is too short. Minimum audio length is 0.1 seconds.{"status":400,"headers":{"access-control-expose-headers":"X-Request-ID","cf-cache-status":"DYNAMIC","cf-ray":"90495d9a6851e80d-ORD","connection":"keep-alive","content-length":"188","content-type":"application/json","date":"Sun, 19 Jan 2025 19:52:31 GMT","openai-organization":"user-zoguqoxxqhzuxsh0raopqxvp","openai-processing-ms":"206","openai-version":"2020-10-01","server":"cloudflare","set-cookie":"__cf_bm=A.TP2HiZXgu1lsBzxI3W15q1YZCAjpVMTPlOyRWJbrw-1737316351-1.0.1.1-HaQ43B2rjZXQFa5237k5zwLuj06XLapGXGV.GNXwXk.pkLiI6LKWudcZkXhkMSG0bSQOYxVaZjgbWQWlVZLMCQ; path=/; expires=Sun, 19-Jan-25 20:22:31 GMT; domain=.api.openai.com; HttpOnly; Secure; SameSite=None, _cfuvid=bxq7qi20HVvI.WzH4LvZlhM1s.ZpGN1UIJ1gD4_D274-1737316351400-0.0.1.1-604800000; path=/; domain=.api.openai.com; HttpOnly; Secure; SameSite=None","strict-transport-security":"max-age=31536000; includeSubDomains; preload","via":"envoy-router-549b6f66cb-s8kvj","x-content-type-options":"nosniff","x-envoy-upstream-service-time":"165","x-ratelimit-limit-requests":"500","x-ratelimit-remaining-requests":"499","x-ratelimit-reset-requests":"120ms","x-request-id":"req_c9ee1b7203ec4297d3eff897831a5567"},"request_id":"req_c9ee1b7203ec4297d3eff897831a5567","error":{"message":"Audio file is too short. Minimum audio length is 0.1 seconds.","type":"invalid_request_error","param":"file","code":"audio_too_short"},"code":"audio_too_short","param":"file","type":"invalid_request_error","stack":"Error: 400 Audio file is too short. Minimum audio length is 0.1 seconds.\n    at APIError.generate (file:///usr/src/app/node_modules/.pnpm/openai@4.79.1_ws@8.18.0/node_modules/openai/error.mjs:41:20)\n    at OpenAI.makeStatusError (file:///usr/src/app/node_modules/.pnpm/openai@4.79.1_ws@8.18.0/node_modules/openai/core.mjs:286:25)\n    at OpenAI.makeRequest (file:///usr/src/app/node_modules/.pnpm/openai@4.79.1_ws@8.18.0/node_modules/openai/core.mjs:330:30)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async TranscriptionService.transcribe (file:///usr/src/app/src/services/TranscriptionService.js:34:35)\n    at async VoiceRecorder.processRotatedRecording (file:///usr/src/app/src/VoiceRecorder.js:102:32)"}
2025-01-19T19:52:31.415Z [31merror[39m: [VoiceRecorder] Error processing recording: 400 Audio file is too short. Minimum audio length is 0.1 seconds.{"status":400,"headers":{"access-control-expose-headers":"X-Request-ID","cf-cache-status":"DYNAMIC","cf-ray":"90495d9a6851e80d-ORD","connection":"keep-alive","content-length":"188","content-type":"application/json","date":"Sun, 19 Jan 2025 19:52:31 GMT","openai-organization":"user-zoguqoxxqhzuxsh0raopqxvp","openai-processing-ms":"206","openai-version":"2020-10-01","server":"cloudflare","set-cookie":"__cf_bm=A.TP2HiZXgu1lsBzxI3W15q1YZCAjpVMTPlOyRWJbrw-1737316351-1.0.1.1-HaQ43B2rjZXQFa5237k5zwLuj06XLapGXGV.GNXwXk.pkLiI6LKWudcZkXhkMSG0bSQOYxVaZjgbWQWlVZLMCQ; path=/; expires=Sun, 19-Jan-25 20:22:31 GMT; domain=.api.openai.com; HttpOnly; Secure; SameSite=None, _cfuvid=bxq7qi20HVvI.WzH4LvZlhM1s.ZpGN1UIJ1gD4_D274-1737316351400-0.0.1.1-604800000; path=/; domain=.api.openai.com; HttpOnly; Secure; SameSite=None","strict-transport-security":"max-age=31536000; includeSubDomains; preload","via":"envoy-router-549b6f66cb-s8kvj","x-content-type-options":"nosniff","x-envoy-upstream-service-time":"165","x-ratelimit-limit-requests":"500","x-ratelimit-remaining-requests":"499","x-ratelimit-reset-requests":"120ms","x-request-id":"req_c9ee1b7203ec4297d3eff897831a5567"},"request_id":"req_c9ee1b7203ec4297d3eff897831a5567","error":{"message":"Audio file is too short. Minimum audio length is 0.1 seconds.","type":"invalid_request_error","param":"file","code":"audio_too_short"},"code":"audio_too_short","param":"file","type":"invalid_request_error","stack":"Error: 400 Audio file is too short. Minimum audio length is 0.1 seconds.\n    at APIError.generate (file:///usr/src/app/node_modules/.pnpm/openai@4.79.1_ws@8.18.0/node_modules/openai/error.mjs:41:20)\n    at OpenAI.makeStatusError (file:///usr/src/app/node_modules/.pnpm/openai@4.79.1_ws@8.18.0/node_modules/openai/core.mjs:286:25)\n    at OpenAI.makeRequest (file:///usr/src/app/node_modules/.pnpm/openai@4.79.1_ws@8.18.0/node_modules/openai/core.mjs:330:30)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async TranscriptionService.transcribe (file:///usr/src/app/src/services/TranscriptionService.js:34:35)\n    at async VoiceRecorder.processRotatedRecording (file:///usr/src/app/src/VoiceRecorder.js:102:32)"}
2025-01-19T19:52:31.415Z [31merror[39m: [VoiceRecorder] Error processing rotated recording: 400 Audio file is too short. Minimum audio length is 0.1 seconds.{"status":400,"headers":{"access-control-expose-headers":"X-Request-ID","cf-cache-status":"DYNAMIC","cf-ray":"90495d9a6851e80d-ORD","connection":"keep-alive","content-length":"188","content-type":"application/json","date":"Sun, 19 Jan 2025 19:52:31 GMT","openai-organization":"user-zoguqoxxqhzuxsh0raopqxvp","openai-processing-ms":"206","openai-version":"2020-10-01","server":"cloudflare","set-cookie":"__cf_bm=A.TP2HiZXgu1lsBzxI3W15q1YZCAjpVMTPlOyRWJbrw-1737316351-1.0.1.1-HaQ43B2rjZXQFa5237k5zwLuj06XLapGXGV.GNXwXk.pkLiI6LKWudcZkXhkMSG0bSQOYxVaZjgbWQWlVZLMCQ; path=/; expires=Sun, 19-Jan-25 20:22:31 GMT; domain=.api.openai.com; HttpOnly; Secure; SameSite=None, _cfuvid=bxq7qi20HVvI.WzH4LvZlhM1s.ZpGN1UIJ1gD4_D274-1737316351400-0.0.1.1-604800000; path=/; domain=.api.openai.com; HttpOnly; Secure; SameSite=None","strict-transport-security":"max-age=31536000; includeSubDomains; preload","via":"envoy-router-549b6f66cb-s8kvj","x-content-type-options":"nosniff","x-envoy-upstream-service-time":"165","x-ratelimit-limit-requests":"500","x-ratelimit-remaining-requests":"499","x-ratelimit-reset-requests":"120ms","x-request-id":"req_c9ee1b7203ec4297d3eff897831a5567"},"request_id":"req_c9ee1b7203ec4297d3eff897831a5567","error":{"message":"Audio file is too short. Minimum audio length is 0.1 seconds.","type":"invalid_request_error","param":"file","code":"audio_too_short"},"code":"audio_too_short","param":"file","type":"invalid_request_error","stack":"Error: 400 Audio file is too short. Minimum audio length is 0.1 seconds.\n    at APIError.generate (file:///usr/src/app/node_modules/.pnpm/openai@4.79.1_ws@8.18.0/node_modules/openai/error.mjs:41:20)\n    at OpenAI.makeStatusError (file:///usr/src/app/node_modules/.pnpm/openai@4.79.1_ws@8.18.0/node_modules/openai/core.mjs:286:25)\n    at OpenAI.makeRequest (file:///usr/src/app/node_modules/.pnpm/openai@4.79.1_ws@8.18.0/node_modules/openai/core.mjs:330:30)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async TranscriptionService.transcribe (file:///usr/src/app/src/services/TranscriptionService.js:34:35)\n    at async VoiceRecorder.processRotatedRecording (file:///usr/src/app/src/VoiceRecorder.js:102:32)"}
2025-01-19T19:54:51.821Z [31merror[39m: [TranscriptionService] Summary generation failed:{"location":"TranscriptionService.generateSummary","error":{"name":"Error","message":"Failed to generate summary","stack":"Error: Failed to generate summary\n    at TranscriptionService.generateSummary (file:///usr/src/app/src/services/TranscriptionService.js:104:31)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async VoiceRecorder.processRotatedRecording (file:///usr/src/app/src/VoiceRecorder.js:109:27)"},"context":{"transcriptLength":750,"transcriptSample":"It's like a soft. You're right, but it's eight inches long. Bigger. A bill of a thought. I go to Lon"}}
2025-01-19T19:55:05.461Z [31merror[39m: [TranscriptionService] Summary generation failed:{"location":"TranscriptionService.generateSummary","error":{"name":"Error","message":"Failed to generate summary","stack":"Error: Failed to generate summary\n    at TranscriptionService.generateSummary (file:///usr/src/app/src/services/TranscriptionService.js:104:31)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async file:///usr/src/app/src/services/SummaryJobService.js:24:33\n    at async Queue.<anonymous> (file:///usr/src/app/src/services/JobService.js:44:24)"},"context":{"transcriptLength":750,"transcriptSample":"It's like a soft. You're right, but it's eight inches long. Bigger. A bill of a thought. I go to Lon"}}
2025-01-19T19:55:05.463Z [31merror[39m: [SummaryJobService] Failed to generate background summary:{"error":"Failed to generate summary: Failed to generate summary","stack":"Error: Failed to generate summary: Failed to generate summary\n    at TranscriptionService.generateSummary (file:///usr/src/app/src/services/TranscriptionService.js:150:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async file:///usr/src/app/src/services/SummaryJobService.js:24:33\n    at async Queue.<anonymous> (file:///usr/src/app/src/services/JobService.js:44:24)","guildId":"1315144523336122469"}
2025-01-19T19:56:46.495Z [31merror[39m: [TranscriptionService] Summary generation failed:{"location":"TranscriptionService.generateSummary","error":{"name":"Error","message":"Failed to generate summary","stack":"Error: Failed to generate summary\n    at TranscriptionService.generateSummary (file:///usr/src/app/src/services/TranscriptionService.js:104:31)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async VoiceRecorder.processRotatedRecording (file:///usr/src/app/src/VoiceRecorder.js:109:27)"},"context":{"transcriptLength":97,"transcriptSample":"Please see the complete disclaimer at https://sites.google.com or at https://sites.google.com.au\n"}}
2025-01-19T19:57:00.370Z [31merror[39m: [TranscriptionService] Summary generation failed:{"location":"TranscriptionService.generateSummary","error":{"name":"Error","message":"Failed to generate summary","stack":"Error: Failed to generate summary\n    at TranscriptionService.generateSummary (file:///usr/src/app/src/services/TranscriptionService.js:104:31)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async file:///usr/src/app/src/services/SummaryJobService.js:24:33\n    at async Queue.<anonymous> (file:///usr/src/app/src/services/JobService.js:44:24)"},"context":{"transcriptLength":97,"transcriptSample":"Please see the complete disclaimer at https://sites.google.com or at https://sites.google.com.au\n"}}
2025-01-19T19:57:00.373Z [31merror[39m: [SummaryJobService] Failed to generate background summary:{"error":"Failed to generate summary: Failed to generate summary","stack":"Error: Failed to generate summary: Failed to generate summary\n    at TranscriptionService.generateSummary (file:///usr/src/app/src/services/TranscriptionService.js:150:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async file:///usr/src/app/src/services/SummaryJobService.js:24:33\n    at async Queue.<anonymous> (file:///usr/src/app/src/services/JobService.js:44:24)","guildId":"1315144523336122469"}
2025-01-19T20:00:45.601Z [31merror[39m: [TranscriptionService] Summary generation failed:{"location":"TranscriptionService.generateSummary","error":{"name":"Error","message":"Failed to generate summary","stack":"Error: Failed to generate summary\n    at TranscriptionService.generateSummary (file:///usr/src/app/src/services/TranscriptionService.js:104:31)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async VoiceRecorder.processRotatedRecording (file:///usr/src/app/src/VoiceRecorder.js:109:27)"},"context":{"transcriptLength":3,"transcriptSample":"I.\n"}}
2025-01-19T20:00:59.535Z [31merror[39m: [TranscriptionService] Summary generation failed:{"location":"TranscriptionService.generateSummary","error":{"name":"Error","message":"Failed to generate summary","stack":"Error: Failed to generate summary\n    at TranscriptionService.generateSummary (file:///usr/src/app/src/services/TranscriptionService.js:104:31)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async file:///usr/src/app/src/services/SummaryJobService.js:24:33\n    at async Queue.<anonymous> (file:///usr/src/app/src/services/JobService.js:44:24)"},"context":{"transcriptLength":3,"transcriptSample":"I.\n"}}
2025-01-19T20:00:59.535Z [31merror[39m: [SummaryJobService] Failed to generate background summary:{"error":"Failed to generate summary: Failed to generate summary","stack":"Error: Failed to generate summary: Failed to generate summary\n    at TranscriptionService.generateSummary (file:///usr/src/app/src/services/TranscriptionService.js:150:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async file:///usr/src/app/src/services/SummaryJobService.js:24:33\n    at async Queue.<anonymous> (file:///usr/src/app/src/services/JobService.js:44:24)","guildId":"1315144523336122469"}
2025-01-19T20:10:48.671Z [31merror[39m: [TranscriptionService] Summary generation failed:{"location":"TranscriptionService.generateSummary","error":{"name":"Error","message":"Failed to generate summary","stack":"Error: Failed to generate summary\n    at TranscriptionService.generateSummary (file:///usr/src/app/src/services/TranscriptionService.js:104:31)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async VoiceRecorder.processRotatedRecording (file:///usr/src/app/src/VoiceRecorder.js:109:27)"},"context":{"transcriptLength":757,"transcriptSample":"I can, I can get it to him. If you want, I could. Yeah, it's a big sample. Here, quick, I'm going to"}}
2025-01-19T20:11:03.069Z [31merror[39m: [TranscriptionService] Summary generation failed:{"location":"TranscriptionService.generateSummary","error":{"name":"Error","message":"Failed to generate summary","stack":"Error: Failed to generate summary\n    at TranscriptionService.generateSummary (file:///usr/src/app/src/services/TranscriptionService.js:104:31)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async file:///usr/src/app/src/services/SummaryJobService.js:24:33\n    at async Queue.<anonymous> (file:///usr/src/app/src/services/JobService.js:44:24)"},"context":{"transcriptLength":757,"transcriptSample":"I can, I can get it to him. If you want, I could. Yeah, it's a big sample. Here, quick, I'm going to"}}
2025-01-19T20:11:03.070Z [31merror[39m: [SummaryJobService] Failed to generate background summary:{"error":"Failed to generate summary: Failed to generate summary","stack":"Error: Failed to generate summary: Failed to generate summary\n    at TranscriptionService.generateSummary (file:///usr/src/app/src/services/TranscriptionService.js:150:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async file:///usr/src/app/src/services/SummaryJobService.js:24:33\n    at async Queue.<anonymous> (file:///usr/src/app/src/services/JobService.js:44:24)","guildId":"1315144523336122469"}
2025-01-19T20:14:47.546Z [31merror[39m: [TranscriptionService] Summary generation failed:{"location":"TranscriptionService.generateSummary","error":{"name":"Error","message":"Failed to generate summary","stack":"Error: Failed to generate summary\n    at TranscriptionService.generateSummary (file:///usr/src/app/src/services/TranscriptionService.js:104:31)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async VoiceRecorder.processRotatedRecording (file:///usr/src/app/src/VoiceRecorder.js:109:27)"},"context":{"transcriptLength":1,"transcriptSample":"\n"}}
2025-01-19T20:15:01.410Z [31merror[39m: [TranscriptionService] Summary generation failed:{"location":"TranscriptionService.generateSummary","error":{"name":"Error","message":"Failed to generate summary","stack":"Error: Failed to generate summary\n    at TranscriptionService.generateSummary (file:///usr/src/app/src/services/TranscriptionService.js:104:31)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async file:///usr/src/app/src/services/SummaryJobService.js:24:33\n    at async Queue.<anonymous> (file:///usr/src/app/src/services/JobService.js:44:24)"},"context":{"transcriptLength":1,"transcriptSample":"\n"}}
2025-01-19T20:15:01.410Z [31merror[39m: [SummaryJobService] Failed to generate background summary:{"error":"Failed to generate summary: Failed to generate summary","stack":"Error: Failed to generate summary: Failed to generate summary\n    at TranscriptionService.generateSummary (file:///usr/src/app/src/services/TranscriptionService.js:150:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async file:///usr/src/app/src/services/SummaryJobService.js:24:33\n    at async Queue.<anonymous> (file:///usr/src/app/src/services/JobService.js:44:24)","guildId":"1315144523336122469"}
2025-01-19T20:18:45.553Z [31merror[39m: [TranscriptionService] Summary generation failed:{"location":"TranscriptionService.generateSummary","error":{"name":"Error","message":"Failed to generate summary","stack":"Error: Failed to generate summary\n    at TranscriptionService.generateSummary (file:///usr/src/app/src/services/TranscriptionService.js:104:31)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async VoiceRecorder.processRotatedRecording (file:///usr/src/app/src/VoiceRecorder.js:109:27)"},"context":{"transcriptLength":32,"transcriptSample":"Transcribed by https://otter.ai\n"}}
2025-01-19T20:18:59.452Z [31merror[39m: [TranscriptionService] Summary generation failed:{"location":"TranscriptionService.generateSummary","error":{"name":"Error","message":"Failed to generate summary","stack":"Error: Failed to generate summary\n    at TranscriptionService.generateSummary (file:///usr/src/app/src/services/TranscriptionService.js:104:31)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async file:///usr/src/app/src/services/SummaryJobService.js:24:33\n    at async Queue.<anonymous> (file:///usr/src/app/src/services/JobService.js:44:24)"},"context":{"transcriptLength":32,"transcriptSample":"Transcribed by https://otter.ai\n"}}
2025-01-19T20:18:59.453Z [31merror[39m: [SummaryJobService] Failed to generate background summary:{"error":"Failed to generate summary: Failed to generate summary","stack":"Error: Failed to generate summary: Failed to generate summary\n    at TranscriptionService.generateSummary (file:///usr/src/app/src/services/TranscriptionService.js:150:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async file:///usr/src/app/src/services/SummaryJobService.js:24:33\n    at async Queue.<anonymous> (file:///usr/src/app/src/services/JobService.js:44:24)","guildId":"1315144523336122469"}
2025-01-19T20:20:58.268Z [31merror[39m: [TranscriptionService] Summary generation failed:{"location":"TranscriptionService.generateSummary","error":{"name":"Error","message":"Failed to generate summary","stack":"Error: Failed to generate summary\n    at TranscriptionService.generateSummary (file:///usr/src/app/src/services/TranscriptionService.js:104:31)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async VoiceRecorder.processRotatedRecording (file:///usr/src/app/src/VoiceRecorder.js:109:27)"},"context":{"transcriptLength":97,"transcriptSample":"guys. Hey, welcome. I'm an outdoor environmentalist. I have lived outdoors in the wilderness for\n"}}
2025-01-19T20:21:13.263Z [31merror[39m: [TranscriptionService] Summary generation failed:{"location":"TranscriptionService.generateSummary","error":{"name":"Error","message":"Failed to generate summary","stack":"Error: Failed to generate summary\n    at TranscriptionService.generateSummary (file:///usr/src/app/src/services/TranscriptionService.js:104:31)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async file:///usr/src/app/src/services/SummaryJobService.js:24:33\n    at async Queue.<anonymous> (file:///usr/src/app/src/services/JobService.js:44:24)"},"context":{"transcriptLength":97,"transcriptSample":"guys. Hey, welcome. I'm an outdoor environmentalist. I have lived outdoors in the wilderness for\n"}}
2025-01-19T20:21:13.264Z [31merror[39m: [SummaryJobService] Failed to generate background summary:{"error":"Failed to generate summary: Failed to generate summary","stack":"Error: Failed to generate summary: Failed to generate summary\n    at TranscriptionService.generateSummary (file:///usr/src/app/src/services/TranscriptionService.js:150:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async file:///usr/src/app/src/services/SummaryJobService.js:24:33\n    at async Queue.<anonymous> (file:///usr/src/app/src/services/JobService.js:44:24)","guildId":"1315144523336122469"}
2025-01-19T20:28:14.731Z [31merror[39m: [TranscriptionService] Summary generation failed:{"location":"TranscriptionService.generateSummary","error":{"name":"Error","message":"Failed to generate summary","stack":"Error: Failed to generate summary\n    at TranscriptionService.generateSummary (file:///usr/src/app/src/services/TranscriptionService.js:104:31)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async VoiceRecorder.processRotatedRecording (file:///usr/src/app/src/VoiceRecorder.js:111:27)"},"context":{"transcriptLength":240,"transcriptSample":"Yeah Beautiful beautiful day here at Excel's course, right? I You picked up All right, thank you Tha"}}
2025-01-19T20:30:15.139Z [31merror[39m: [TranscriptionService] Summary generation failed:{"location":"TranscriptionService.generateSummary","error":{"name":"Error","message":"Failed to generate summary","stack":"Error: Failed to generate summary\n    at TranscriptionService.generateSummary (file:///usr/src/app/src/services/TranscriptionService.js:104:31)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async VoiceRecorder.processRotatedRecording (file:///usr/src/app/src/VoiceRecorder.js:111:27)"},"context":{"transcriptLength":871,"transcriptSample":"I was on a business call, a big merger, buddy. Bob, I don't have time for this. I'm on the link. I s"}}
2025-01-19T20:30:28.863Z [31merror[39m: [TranscriptionService] Summary generation failed:{"location":"TranscriptionService.generateSummary","error":{"name":"Error","message":"Failed to generate summary","stack":"Error: Failed to generate summary\n    at TranscriptionService.generateSummary (file:///usr/src/app/src/services/TranscriptionService.js:104:31)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async file:///usr/src/app/src/services/SummaryJobService.js:25:33\n    at async Queue.<anonymous> (file:///usr/src/app/src/services/JobService.js:44:24)"},"context":{"transcriptLength":871,"transcriptSample":"I was on a business call, a big merger, buddy. Bob, I don't have time for this. I'm on the link. I s"}}
2025-01-19T20:30:28.864Z [31merror[39m: [SummaryJobService] Failed to generate background summary:{"error":"Failed to generate summary: Failed to generate summary","stack":"Error: Failed to generate summary: Failed to generate summary\n    at TranscriptionService.generateSummary (file:///usr/src/app/src/services/TranscriptionService.js:150:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async file:///usr/src/app/src/services/SummaryJobService.js:25:33\n    at async Queue.<anonymous> (file:///usr/src/app/src/services/JobService.js:44:24)","guildId":"1315144523336122469"}
2025-01-19T20:38:10.951Z [31merror[39m: [TranscriptionService] Summary generation failed:{"location":"TranscriptionService.generateSummary","error":{"name":"Error","message":"Failed to generate summary","stack":"Error: Failed to generate summary\n    at TranscriptionService.generateSummary (file:///usr/src/app/src/services/TranscriptionService.js:104:31)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async VoiceRecorder.processRotatedRecording (file:///usr/src/app/src/VoiceRecorder.js:111:27)"},"context":{"transcriptLength":10,"transcriptSample":"It's very\n"}}
2025-01-19T20:38:24.709Z [31merror[39m: [TranscriptionService] Summary generation failed:{"location":"TranscriptionService.generateSummary","error":{"name":"Error","message":"Failed to generate summary","stack":"Error: Failed to generate summary\n    at TranscriptionService.generateSummary (file:///usr/src/app/src/services/TranscriptionService.js:104:31)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async file:///usr/src/app/src/services/SummaryJobService.js:25:33\n    at async Queue.<anonymous> (file:///usr/src/app/src/services/JobService.js:44:24)"},"context":{"transcriptLength":10,"transcriptSample":"It's very\n"}}
2025-01-19T20:38:24.710Z [31merror[39m: [SummaryJobService] Failed to generate background summary:{"error":"Failed to generate summary: Failed to generate summary","stack":"Error: Failed to generate summary: Failed to generate summary\n    at TranscriptionService.generateSummary (file:///usr/src/app/src/services/TranscriptionService.js:150:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async file:///usr/src/app/src/services/SummaryJobService.js:25:33\n    at async Queue.<anonymous> (file:///usr/src/app/src/services/JobService.js:44:24)","guildId":"1315144523336122469"}
2025-01-19T20:41:56.656Z [31merror[39m: [TranscriptionService] Transcription failed: 400 Audio file is too short. Minimum audio length is 0.1 seconds.{"status":400,"headers":{"access-control-expose-headers":"X-Request-ID","cf-cache-status":"DYNAMIC","cf-ray":"9049a5fe8c5c1101-ORD","connection":"keep-alive","content-length":"188","content-type":"application/json","date":"Sun, 19 Jan 2025 20:41:56 GMT","openai-organization":"user-zoguqoxxqhzuxsh0raopqxvp","openai-processing-ms":"159","openai-version":"2020-10-01","server":"cloudflare","set-cookie":"__cf_bm=Vrp9.vFCmYYOiBkQbtYWIUXiNBBKgKiFd7OBzKgvvNs-1737319316-1.0.1.1-L647w7huuwXoXh9DwHtYnBdQ80YFTL2oOJs7r_1W8nP88HEna0cxfPfdwLmlg58GVDWJ4ZYfLNjMrjhKwIoEBw; path=/; expires=Sun, 19-Jan-25 21:11:56 GMT; domain=.api.openai.com; HttpOnly; Secure; SameSite=None, _cfuvid=F0MKwfjrPj06uUaHjZhuZ8nVItop.45LYbIPZzkDxpk-1737319316721-0.0.1.1-604800000; path=/; domain=.api.openai.com; HttpOnly; Secure; SameSite=None","strict-transport-security":"max-age=31536000; includeSubDomains; preload","via":"envoy-router-549b6f66cb-vvs86","x-content-type-options":"nosniff","x-envoy-upstream-service-time":"144","x-ratelimit-limit-requests":"500","x-ratelimit-remaining-requests":"499","x-ratelimit-reset-requests":"120ms","x-request-id":"req_8381aa91786f58cd6100439c9eff812c"},"request_id":"req_8381aa91786f58cd6100439c9eff812c","error":{"message":"Audio file is too short. Minimum audio length is 0.1 seconds.","type":"invalid_request_error","param":"file","code":"audio_too_short"},"code":"audio_too_short","param":"file","type":"invalid_request_error","stack":"Error: 400 Audio file is too short. Minimum audio length is 0.1 seconds.\n    at APIError.generate (file:///usr/src/app/node_modules/.pnpm/openai@4.79.1_ws@8.18.0/node_modules/openai/error.mjs:41:20)\n    at OpenAI.makeStatusError (file:///usr/src/app/node_modules/.pnpm/openai@4.79.1_ws@8.18.0/node_modules/openai/core.mjs:286:25)\n    at OpenAI.makeRequest (file:///usr/src/app/node_modules/.pnpm/openai@4.79.1_ws@8.18.0/node_modules/openai/core.mjs:330:30)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async TranscriptionService.transcribe (file:///usr/src/app/src/services/TranscriptionService.js:34:35)\n    at async VoiceRecorder.processRotatedRecording (file:///usr/src/app/src/VoiceRecorder.js:104:32)"}
2025-01-19T20:41:56.660Z [31merror[39m: [VoiceRecorder] Error processing recording: 400 Audio file is too short. Minimum audio length is 0.1 seconds.{"status":400,"headers":{"access-control-expose-headers":"X-Request-ID","cf-cache-status":"DYNAMIC","cf-ray":"9049a5fe8c5c1101-ORD","connection":"keep-alive","content-length":"188","content-type":"application/json","date":"Sun, 19 Jan 2025 20:41:56 GMT","openai-organization":"user-zoguqoxxqhzuxsh0raopqxvp","openai-processing-ms":"159","openai-version":"2020-10-01","server":"cloudflare","set-cookie":"__cf_bm=Vrp9.vFCmYYOiBkQbtYWIUXiNBBKgKiFd7OBzKgvvNs-1737319316-1.0.1.1-L647w7huuwXoXh9DwHtYnBdQ80YFTL2oOJs7r_1W8nP88HEna0cxfPfdwLmlg58GVDWJ4ZYfLNjMrjhKwIoEBw; path=/; expires=Sun, 19-Jan-25 21:11:56 GMT; domain=.api.openai.com; HttpOnly; Secure; SameSite=None, _cfuvid=F0MKwfjrPj06uUaHjZhuZ8nVItop.45LYbIPZzkDxpk-1737319316721-0.0.1.1-604800000; path=/; domain=.api.openai.com; HttpOnly; Secure; SameSite=None","strict-transport-security":"max-age=31536000; includeSubDomains; preload","via":"envoy-router-549b6f66cb-vvs86","x-content-type-options":"nosniff","x-envoy-upstream-service-time":"144","x-ratelimit-limit-requests":"500","x-ratelimit-remaining-requests":"499","x-ratelimit-reset-requests":"120ms","x-request-id":"req_8381aa91786f58cd6100439c9eff812c"},"request_id":"req_8381aa91786f58cd6100439c9eff812c","error":{"message":"Audio file is too short. Minimum audio length is 0.1 seconds.","type":"invalid_request_error","param":"file","code":"audio_too_short"},"code":"audio_too_short","param":"file","type":"invalid_request_error","stack":"Error: 400 Audio file is too short. Minimum audio length is 0.1 seconds.\n    at APIError.generate (file:///usr/src/app/node_modules/.pnpm/openai@4.79.1_ws@8.18.0/node_modules/openai/error.mjs:41:20)\n    at OpenAI.makeStatusError (file:///usr/src/app/node_modules/.pnpm/openai@4.79.1_ws@8.18.0/node_modules/openai/core.mjs:286:25)\n    at OpenAI.makeRequest (file:///usr/src/app/node_modules/.pnpm/openai@4.79.1_ws@8.18.0/node_modules/openai/core.mjs:330:30)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async TranscriptionService.transcribe (file:///usr/src/app/src/services/TranscriptionService.js:34:35)\n    at async VoiceRecorder.processRotatedRecording (file:///usr/src/app/src/VoiceRecorder.js:104:32)"}
2025-01-19T20:41:56.660Z [31merror[39m: [VoiceRecorder] Error processing rotated recording: 400 Audio file is too short. Minimum audio length is 0.1 seconds.{"status":400,"headers":{"access-control-expose-headers":"X-Request-ID","cf-cache-status":"DYNAMIC","cf-ray":"9049a5fe8c5c1101-ORD","connection":"keep-alive","content-length":"188","content-type":"application/json","date":"Sun, 19 Jan 2025 20:41:56 GMT","openai-organization":"user-zoguqoxxqhzuxsh0raopqxvp","openai-processing-ms":"159","openai-version":"2020-10-01","server":"cloudflare","set-cookie":"__cf_bm=Vrp9.vFCmYYOiBkQbtYWIUXiNBBKgKiFd7OBzKgvvNs-1737319316-1.0.1.1-L647w7huuwXoXh9DwHtYnBdQ80YFTL2oOJs7r_1W8nP88HEna0cxfPfdwLmlg58GVDWJ4ZYfLNjMrjhKwIoEBw; path=/; expires=Sun, 19-Jan-25 21:11:56 GMT; domain=.api.openai.com; HttpOnly; Secure; SameSite=None, _cfuvid=F0MKwfjrPj06uUaHjZhuZ8nVItop.45LYbIPZzkDxpk-1737319316721-0.0.1.1-604800000; path=/; domain=.api.openai.com; HttpOnly; Secure; SameSite=None","strict-transport-security":"max-age=31536000; includeSubDomains; preload","via":"envoy-router-549b6f66cb-vvs86","x-content-type-options":"nosniff","x-envoy-upstream-service-time":"144","x-ratelimit-limit-requests":"500","x-ratelimit-remaining-requests":"499","x-ratelimit-reset-requests":"120ms","x-request-id":"req_8381aa91786f58cd6100439c9eff812c"},"request_id":"req_8381aa91786f58cd6100439c9eff812c","error":{"message":"Audio file is too short. Minimum audio length is 0.1 seconds.","type":"invalid_request_error","param":"file","code":"audio_too_short"},"code":"audio_too_short","param":"file","type":"invalid_request_error","stack":"Error: 400 Audio file is too short. Minimum audio length is 0.1 seconds.\n    at APIError.generate (file:///usr/src/app/node_modules/.pnpm/openai@4.79.1_ws@8.18.0/node_modules/openai/error.mjs:41:20)\n    at OpenAI.makeStatusError (file:///usr/src/app/node_modules/.pnpm/openai@4.79.1_ws@8.18.0/node_modules/openai/core.mjs:286:25)\n    at OpenAI.makeRequest (file:///usr/src/app/node_modules/.pnpm/openai@4.79.1_ws@8.18.0/node_modules/openai/core.mjs:330:30)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async TranscriptionService.transcribe (file:///usr/src/app/src/services/TranscriptionService.js:34:35)\n    at async VoiceRecorder.processRotatedRecording (file:///usr/src/app/src/VoiceRecorder.js:104:32)"}
2025-01-19T20:46:13.456Z [31merror[39m: [TranscriptionService] Summary generation failed:{"location":"TranscriptionService.generateSummary","error":{"name":"Error","message":"Failed to generate summary","stack":"Error: Failed to generate summary\n    at TranscriptionService.generateSummary (file:///usr/src/app/src/services/TranscriptionService.js:104:31)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async VoiceRecorder.processRotatedRecording (file:///usr/src/app/src/VoiceRecorder.js:111:27)"},"context":{"transcriptLength":802,"transcriptSample":"I'm going to show you a scene from Unresolved Crimes. Today on Unresolved Crimes. Unresolved Crimes."}}
2025-01-19T20:46:27.247Z [31merror[39m: [TranscriptionService] Summary generation failed:{"location":"TranscriptionService.generateSummary","error":{"name":"Error","message":"Failed to generate summary","stack":"Error: Failed to generate summary\n    at TranscriptionService.generateSummary (file:///usr/src/app/src/services/TranscriptionService.js:104:31)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async file:///usr/src/app/src/services/SummaryJobService.js:25:33\n    at async Queue.<anonymous> (file:///usr/src/app/src/services/JobService.js:44:24)"},"context":{"transcriptLength":802,"transcriptSample":"I'm going to show you a scene from Unresolved Crimes. Today on Unresolved Crimes. Unresolved Crimes."}}
2025-01-19T20:46:27.249Z [31merror[39m: [SummaryJobService] Failed to generate background summary:{"error":"Failed to generate summary: Failed to generate summary","stack":"Error: Failed to generate summary: Failed to generate summary\n    at TranscriptionService.generateSummary (file:///usr/src/app/src/services/TranscriptionService.js:150:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async file:///usr/src/app/src/services/SummaryJobService.js:25:33\n    at async Queue.<anonymous> (file:///usr/src/app/src/services/JobService.js:44:24)","guildId":"1315144523336122469"}
2025-01-19T20:49:43.580Z [31merror[39m: Error executing command record: Unknown interaction{"requestBody":{"files":[],"json":{"type":4,"data":{"content":"❌ **Error:** Failed to start recording. Please try again.","tts":false,"enforce_nonce":false,"flags":64}}},"rawError":{"message":"Unknown interaction","code":10062},"code":10062,"status":404,"method":"POST","url":"https://discord.com/api/v10/interactions/1330640358022975600/aW50ZXJhY3Rpb246MTMzMDY0MDM1ODAyMjk3NTYwMDpPdHZoMXRxWkh1clpIWVFFdUtUZmYwTEd0SmR6NE1wMlJoVVhGN2lZamdSQ3dqUTdiVFNEYVZVMjBUNkdHTnRaVjZTMTFTaGx4SkFzdEhxSzJiZUUxMUlNTUZ3ZnJsZTViRnpTMlhyb0M3YlRsb245Q0hwTzlxQkE4SUVaQUMzdA/callback?with_response=false","stack":"DiscordAPIError[10062]: Unknown interaction\n    at handleErrors (/usr/src/app/node_modules/.pnpm/@discordjs+rest@2.4.2/node_modules/@discordjs/rest/dist/index.js:727:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async BurstHandler.runRequest (/usr/src/app/node_modules/.pnpm/@discordjs+rest@2.4.2/node_modules/@discordjs/rest/dist/index.js:831:23)\n    at async _REST.request (/usr/src/app/node_modules/.pnpm/@discordjs+rest@2.4.2/node_modules/@discordjs/rest/dist/index.js:1272:22)\n    at async ChatInputCommandInteraction.reply (/usr/src/app/node_modules/.pnpm/discord.js@14.17.3/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:194:22)\n    at async handleReply (file:///usr/src/app/src/utils/interactionHelper.js:6:13)\n    at async RecordCommand.execute (file:///usr/src/app/src/commands/audio/RecordCommand.js:60:13)\n    at async CommandRegistry.handleCommand (file:///usr/src/app/src/commands/audio/CommandRegistry.js:65:13)\n    at async Bot.handleInteraction (file:///usr/src/app/src/bot.js:77:13)"}
2025-01-19T20:49:43.582Z [31merror[39m: Error handling command: Unknown interaction{"requestBody":{"files":[],"json":{"type":4,"data":{"content":"❌ **Error:** Failed to start recording. Please try again.","tts":false,"enforce_nonce":false,"flags":64}}},"rawError":{"message":"Unknown interaction","code":10062},"code":10062,"status":404,"method":"POST","url":"https://discord.com/api/v10/interactions/1330640358022975600/aW50ZXJhY3Rpb246MTMzMDY0MDM1ODAyMjk3NTYwMDpPdHZoMXRxWkh1clpIWVFFdUtUZmYwTEd0SmR6NE1wMlJoVVhGN2lZamdSQ3dqUTdiVFNEYVZVMjBUNkdHTnRaVjZTMTFTaGx4SkFzdEhxSzJiZUUxMUlNTUZ3ZnJsZTViRnpTMlhyb0M3YlRsb245Q0hwTzlxQkE4SUVaQUMzdA/callback?with_response=false","stack":"DiscordAPIError[10062]: Unknown interaction\n    at handleErrors (/usr/src/app/node_modules/.pnpm/@discordjs+rest@2.4.2/node_modules/@discordjs/rest/dist/index.js:727:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async BurstHandler.runRequest (/usr/src/app/node_modules/.pnpm/@discordjs+rest@2.4.2/node_modules/@discordjs/rest/dist/index.js:831:23)\n    at async _REST.request (/usr/src/app/node_modules/.pnpm/@discordjs+rest@2.4.2/node_modules/@discordjs/rest/dist/index.js:1272:22)\n    at async ChatInputCommandInteraction.reply (/usr/src/app/node_modules/.pnpm/discord.js@14.17.3/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:194:22)\n    at async handleReply (file:///usr/src/app/src/utils/interactionHelper.js:6:13)\n    at async RecordCommand.execute (file:///usr/src/app/src/commands/audio/RecordCommand.js:60:13)\n    at async CommandRegistry.handleCommand (file:///usr/src/app/src/commands/audio/CommandRegistry.js:65:13)\n    at async Bot.handleInteraction (file:///usr/src/app/src/bot.js:77:13)"}
2025-01-19T20:49:43.583Z [31merror[39m: Discord client error: Unknown interaction{"requestBody":{"files":[],"json":{"type":4,"data":{"content":"❌ **Error:** Failed to start recording. Please try again.","tts":false,"enforce_nonce":false,"flags":64}}},"rawError":{"message":"Unknown interaction","code":10062},"code":10062,"status":404,"method":"POST","url":"https://discord.com/api/v10/interactions/1330640358022975600/aW50ZXJhY3Rpb246MTMzMDY0MDM1ODAyMjk3NTYwMDpPdHZoMXRxWkh1clpIWVFFdUtUZmYwTEd0SmR6NE1wMlJoVVhGN2lZamdSQ3dqUTdiVFNEYVZVMjBUNkdHTnRaVjZTMTFTaGx4SkFzdEhxSzJiZUUxMUlNTUZ3ZnJsZTViRnpTMlhyb0M3YlRsb245Q0hwTzlxQkE4SUVaQUMzdA/callback?with_response=false","stack":"DiscordAPIError[10062]: Unknown interaction\n    at handleErrors (/usr/src/app/node_modules/.pnpm/@discordjs+rest@2.4.2/node_modules/@discordjs/rest/dist/index.js:727:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async BurstHandler.runRequest (/usr/src/app/node_modules/.pnpm/@discordjs+rest@2.4.2/node_modules/@discordjs/rest/dist/index.js:831:23)\n    at async _REST.request (/usr/src/app/node_modules/.pnpm/@discordjs+rest@2.4.2/node_modules/@discordjs/rest/dist/index.js:1272:22)\n    at async ChatInputCommandInteraction.reply (/usr/src/app/node_modules/.pnpm/discord.js@14.17.3/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:194:22)\n    at async handleReply (file:///usr/src/app/src/utils/interactionHelper.js:6:13)\n    at async RecordCommand.execute (file:///usr/src/app/src/commands/audio/RecordCommand.js:60:13)\n    at async CommandRegistry.handleCommand (file:///usr/src/app/src/commands/audio/CommandRegistry.js:65:13)\n    at async Bot.handleInteraction (file:///usr/src/app/src/bot.js:77:13)"}
2025-01-19T20:49:52.055Z [31merror[39m: Error executing command record: deferReplyIfNeeded is not defined{"stack":"ReferenceError: deferReplyIfNeeded is not defined\n    at RecordCommand.execute (file:///usr/src/app/src/commands/audio/RecordCommand.js:31:13)\n    at CommandRegistry.handleCommand (file:///usr/src/app/src/commands/audio/CommandRegistry.js:66:25)\n    at Bot.handleInteraction (file:///usr/src/app/src/bot.js:77:40)\n    at Client.emit (node:events:517:28)\n    at InteractionCreateAction.handle (/usr/src/app/node_modules/.pnpm/discord.js@14.17.3/node_modules/discord.js/src/client/actions/InteractionCreate.js:97:12)\n    at module.exports [as INTERACTION_CREATE] (/usr/src/app/node_modules/.pnpm/discord.js@14.17.3/node_modules/discord.js/src/client/websocket/handlers/INTERACTION_CREATE.js:4:36)\n    at WebSocketManager.handlePacket (/usr/src/app/node_modules/.pnpm/discord.js@14.17.3/node_modules/discord.js/src/client/websocket/WebSocketManager.js:348:31)\n    at WebSocketManager.<anonymous> (/usr/src/app/node_modules/.pnpm/discord.js@14.17.3/node_modules/discord.js/src/client/websocket/WebSocketManager.js:232:12)\n    at WebSocketManager.emit (/usr/src/app/node_modules/.pnpm/@vladfrangu+async_event_emitter@2.4.6/node_modules/@vladfrangu/async_event_emitter/dist/index.cjs:287:31)\n    at WebSocketShard.<anonymous> (/usr/src/app/node_modules/.pnpm/@discordjs+ws@1.2.0/node_modules/@discordjs/ws/dist/index.js:1190:51)"}
2025-01-19T20:49:52.057Z [31merror[39m: Error handling command: deferReplyIfNeeded is not defined{"stack":"ReferenceError: deferReplyIfNeeded is not defined\n    at RecordCommand.execute (file:///usr/src/app/src/commands/audio/RecordCommand.js:31:13)\n    at CommandRegistry.handleCommand (file:///usr/src/app/src/commands/audio/CommandRegistry.js:66:25)\n    at Bot.handleInteraction (file:///usr/src/app/src/bot.js:77:40)\n    at Client.emit (node:events:517:28)\n    at InteractionCreateAction.handle (/usr/src/app/node_modules/.pnpm/discord.js@14.17.3/node_modules/discord.js/src/client/actions/InteractionCreate.js:97:12)\n    at module.exports [as INTERACTION_CREATE] (/usr/src/app/node_modules/.pnpm/discord.js@14.17.3/node_modules/discord.js/src/client/websocket/handlers/INTERACTION_CREATE.js:4:36)\n    at WebSocketManager.handlePacket (/usr/src/app/node_modules/.pnpm/discord.js@14.17.3/node_modules/discord.js/src/client/websocket/WebSocketManager.js:348:31)\n    at WebSocketManager.<anonymous> (/usr/src/app/node_modules/.pnpm/discord.js@14.17.3/node_modules/discord.js/src/client/websocket/WebSocketManager.js:232:12)\n    at WebSocketManager.emit (/usr/src/app/node_modules/.pnpm/@vladfrangu+async_event_emitter@2.4.6/node_modules/@vladfrangu/async_event_emitter/dist/index.cjs:287:31)\n    at WebSocketShard.<anonymous> (/usr/src/app/node_modules/.pnpm/@discordjs+ws@1.2.0/node_modules/@discordjs/ws/dist/index.js:1190:51)"}
2025-01-19T20:49:52.058Z [31merror[39m: Discord client error: deferReplyIfNeeded is not defined{"stack":"ReferenceError: deferReplyIfNeeded is not defined\n    at RecordCommand.execute (file:///usr/src/app/src/commands/audio/RecordCommand.js:31:13)\n    at CommandRegistry.handleCommand (file:///usr/src/app/src/commands/audio/CommandRegistry.js:66:25)\n    at Bot.handleInteraction (file:///usr/src/app/src/bot.js:77:40)\n    at Client.emit (node:events:517:28)\n    at InteractionCreateAction.handle (/usr/src/app/node_modules/.pnpm/discord.js@14.17.3/node_modules/discord.js/src/client/actions/InteractionCreate.js:97:12)\n    at module.exports [as INTERACTION_CREATE] (/usr/src/app/node_modules/.pnpm/discord.js@14.17.3/node_modules/discord.js/src/client/websocket/handlers/INTERACTION_CREATE.js:4:36)\n    at WebSocketManager.handlePacket (/usr/src/app/node_modules/.pnpm/discord.js@14.17.3/node_modules/discord.js/src/client/websocket/WebSocketManager.js:348:31)\n    at WebSocketManager.<anonymous> (/usr/src/app/node_modules/.pnpm/discord.js@14.17.3/node_modules/discord.js/src/client/websocket/WebSocketManager.js:232:12)\n    at WebSocketManager.emit (/usr/src/app/node_modules/.pnpm/@vladfrangu+async_event_emitter@2.4.6/node_modules/@vladfrangu/async_event_emitter/dist/index.cjs:287:31)\n    at WebSocketShard.<anonymous> (/usr/src/app/node_modules/.pnpm/@discordjs+ws@1.2.0/node_modules/@discordjs/ws/dist/index.js:1190:51)"}
2025-01-19T20:49:55.244Z [31merror[39m: Error executing command record: deferReplyIfNeeded is not defined{"stack":"ReferenceError: deferReplyIfNeeded is not defined\n    at RecordCommand.execute (file:///usr/src/app/src/commands/audio/RecordCommand.js:31:13)\n    at CommandRegistry.handleCommand (file:///usr/src/app/src/commands/audio/CommandRegistry.js:66:25)\n    at Bot.handleInteraction (file:///usr/src/app/src/bot.js:77:40)\n    at Client.emit (node:events:517:28)\n    at InteractionCreateAction.handle (/usr/src/app/node_modules/.pnpm/discord.js@14.17.3/node_modules/discord.js/src/client/actions/InteractionCreate.js:97:12)\n    at module.exports [as INTERACTION_CREATE] (/usr/src/app/node_modules/.pnpm/discord.js@14.17.3/node_modules/discord.js/src/client/websocket/handlers/INTERACTION_CREATE.js:4:36)\n    at WebSocketManager.handlePacket (/usr/src/app/node_modules/.pnpm/discord.js@14.17.3/node_modules/discord.js/src/client/websocket/WebSocketManager.js:348:31)\n    at WebSocketManager.<anonymous> (/usr/src/app/node_modules/.pnpm/discord.js@14.17.3/node_modules/discord.js/src/client/websocket/WebSocketManager.js:232:12)\n    at WebSocketManager.emit (/usr/src/app/node_modules/.pnpm/@vladfrangu+async_event_emitter@2.4.6/node_modules/@vladfrangu/async_event_emitter/dist/index.cjs:287:31)\n    at WebSocketShard.<anonymous> (/usr/src/app/node_modules/.pnpm/@discordjs+ws@1.2.0/node_modules/@discordjs/ws/dist/index.js:1190:51)"}
2025-01-19T20:49:55.246Z [31merror[39m: Error handling command: deferReplyIfNeeded is not defined{"stack":"ReferenceError: deferReplyIfNeeded is not defined\n    at RecordCommand.execute (file:///usr/src/app/src/commands/audio/RecordCommand.js:31:13)\n    at CommandRegistry.handleCommand (file:///usr/src/app/src/commands/audio/CommandRegistry.js:66:25)\n    at Bot.handleInteraction (file:///usr/src/app/src/bot.js:77:40)\n    at Client.emit (node:events:517:28)\n    at InteractionCreateAction.handle (/usr/src/app/node_modules/.pnpm/discord.js@14.17.3/node_modules/discord.js/src/client/actions/InteractionCreate.js:97:12)\n    at module.exports [as INTERACTION_CREATE] (/usr/src/app/node_modules/.pnpm/discord.js@14.17.3/node_modules/discord.js/src/client/websocket/handlers/INTERACTION_CREATE.js:4:36)\n    at WebSocketManager.handlePacket (/usr/src/app/node_modules/.pnpm/discord.js@14.17.3/node_modules/discord.js/src/client/websocket/WebSocketManager.js:348:31)\n    at WebSocketManager.<anonymous> (/usr/src/app/node_modules/.pnpm/discord.js@14.17.3/node_modules/discord.js/src/client/websocket/WebSocketManager.js:232:12)\n    at WebSocketManager.emit (/usr/src/app/node_modules/.pnpm/@vladfrangu+async_event_emitter@2.4.6/node_modules/@vladfrangu/async_event_emitter/dist/index.cjs:287:31)\n    at WebSocketShard.<anonymous> (/usr/src/app/node_modules/.pnpm/@discordjs+ws@1.2.0/node_modules/@discordjs/ws/dist/index.js:1190:51)"}
2025-01-19T20:49:55.248Z [31merror[39m: Discord client error: deferReplyIfNeeded is not defined{"stack":"ReferenceError: deferReplyIfNeeded is not defined\n    at RecordCommand.execute (file:///usr/src/app/src/commands/audio/RecordCommand.js:31:13)\n    at CommandRegistry.handleCommand (file:///usr/src/app/src/commands/audio/CommandRegistry.js:66:25)\n    at Bot.handleInteraction (file:///usr/src/app/src/bot.js:77:40)\n    at Client.emit (node:events:517:28)\n    at InteractionCreateAction.handle (/usr/src/app/node_modules/.pnpm/discord.js@14.17.3/node_modules/discord.js/src/client/actions/InteractionCreate.js:97:12)\n    at module.exports [as INTERACTION_CREATE] (/usr/src/app/node_modules/.pnpm/discord.js@14.17.3/node_modules/discord.js/src/client/websocket/handlers/INTERACTION_CREATE.js:4:36)\n    at WebSocketManager.handlePacket (/usr/src/app/node_modules/.pnpm/discord.js@14.17.3/node_modules/discord.js/src/client/websocket/WebSocketManager.js:348:31)\n    at WebSocketManager.<anonymous> (/usr/src/app/node_modules/.pnpm/discord.js@14.17.3/node_modules/discord.js/src/client/websocket/WebSocketManager.js:232:12)\n    at WebSocketManager.emit (/usr/src/app/node_modules/.pnpm/@vladfrangu+async_event_emitter@2.4.6/node_modules/@vladfrangu/async_event_emitter/dist/index.cjs:287:31)\n    at WebSocketShard.<anonymous> (/usr/src/app/node_modules/.pnpm/@discordjs+ws@1.2.0/node_modules/@discordjs/ws/dist/index.js:1190:51)"}
2025-01-19T20:50:04.932Z [31merror[39m: Error executing command record: deferReplyIfNeeded is not defined{"stack":"ReferenceError: deferReplyIfNeeded is not defined\n    at RecordCommand.execute (file:///usr/src/app/src/commands/audio/RecordCommand.js:31:13)\n    at CommandRegistry.handleCommand (file:///usr/src/app/src/commands/audio/CommandRegistry.js:66:25)\n    at Bot.handleInteraction (file:///usr/src/app/src/bot.js:77:40)\n    at Client.emit (node:events:517:28)\n    at InteractionCreateAction.handle (/usr/src/app/node_modules/.pnpm/discord.js@14.17.3/node_modules/discord.js/src/client/actions/InteractionCreate.js:97:12)\n    at module.exports [as INTERACTION_CREATE] (/usr/src/app/node_modules/.pnpm/discord.js@14.17.3/node_modules/discord.js/src/client/websocket/handlers/INTERACTION_CREATE.js:4:36)\n    at WebSocketManager.handlePacket (/usr/src/app/node_modules/.pnpm/discord.js@14.17.3/node_modules/discord.js/src/client/websocket/WebSocketManager.js:348:31)\n    at WebSocketManager.<anonymous> (/usr/src/app/node_modules/.pnpm/discord.js@14.17.3/node_modules/discord.js/src/client/websocket/WebSocketManager.js:232:12)\n    at WebSocketManager.emit (/usr/src/app/node_modules/.pnpm/@vladfrangu+async_event_emitter@2.4.6/node_modules/@vladfrangu/async_event_emitter/dist/index.cjs:287:31)\n    at WebSocketShard.<anonymous> (/usr/src/app/node_modules/.pnpm/@discordjs+ws@1.2.0/node_modules/@discordjs/ws/dist/index.js:1190:51)"}
2025-01-19T20:50:04.934Z [31merror[39m: Error handling command: deferReplyIfNeeded is not defined{"stack":"ReferenceError: deferReplyIfNeeded is not defined\n    at RecordCommand.execute (file:///usr/src/app/src/commands/audio/RecordCommand.js:31:13)\n    at CommandRegistry.handleCommand (file:///usr/src/app/src/commands/audio/CommandRegistry.js:66:25)\n    at Bot.handleInteraction (file:///usr/src/app/src/bot.js:77:40)\n    at Client.emit (node:events:517:28)\n    at InteractionCreateAction.handle (/usr/src/app/node_modules/.pnpm/discord.js@14.17.3/node_modules/discord.js/src/client/actions/InteractionCreate.js:97:12)\n    at module.exports [as INTERACTION_CREATE] (/usr/src/app/node_modules/.pnpm/discord.js@14.17.3/node_modules/discord.js/src/client/websocket/handlers/INTERACTION_CREATE.js:4:36)\n    at WebSocketManager.handlePacket (/usr/src/app/node_modules/.pnpm/discord.js@14.17.3/node_modules/discord.js/src/client/websocket/WebSocketManager.js:348:31)\n    at WebSocketManager.<anonymous> (/usr/src/app/node_modules/.pnpm/discord.js@14.17.3/node_modules/discord.js/src/client/websocket/WebSocketManager.js:232:12)\n    at WebSocketManager.emit (/usr/src/app/node_modules/.pnpm/@vladfrangu+async_event_emitter@2.4.6/node_modules/@vladfrangu/async_event_emitter/dist/index.cjs:287:31)\n    at WebSocketShard.<anonymous> (/usr/src/app/node_modules/.pnpm/@discordjs+ws@1.2.0/node_modules/@discordjs/ws/dist/index.js:1190:51)"}
2025-01-19T20:50:04.936Z [31merror[39m: Discord client error: deferReplyIfNeeded is not defined{"stack":"ReferenceError: deferReplyIfNeeded is not defined\n    at RecordCommand.execute (file:///usr/src/app/src/commands/audio/RecordCommand.js:31:13)\n    at CommandRegistry.handleCommand (file:///usr/src/app/src/commands/audio/CommandRegistry.js:66:25)\n    at Bot.handleInteraction (file:///usr/src/app/src/bot.js:77:40)\n    at Client.emit (node:events:517:28)\n    at InteractionCreateAction.handle (/usr/src/app/node_modules/.pnpm/discord.js@14.17.3/node_modules/discord.js/src/client/actions/InteractionCreate.js:97:12)\n    at module.exports [as INTERACTION_CREATE] (/usr/src/app/node_modules/.pnpm/discord.js@14.17.3/node_modules/discord.js/src/client/websocket/handlers/INTERACTION_CREATE.js:4:36)\n    at WebSocketManager.handlePacket (/usr/src/app/node_modules/.pnpm/discord.js@14.17.3/node_modules/discord.js/src/client/websocket/WebSocketManager.js:348:31)\n    at WebSocketManager.<anonymous> (/usr/src/app/node_modules/.pnpm/discord.js@14.17.3/node_modules/discord.js/src/client/websocket/WebSocketManager.js:232:12)\n    at WebSocketManager.emit (/usr/src/app/node_modules/.pnpm/@vladfrangu+async_event_emitter@2.4.6/node_modules/@vladfrangu/async_event_emitter/dist/index.cjs:287:31)\n    at WebSocketShard.<anonymous> (/usr/src/app/node_modules/.pnpm/@discordjs+ws@1.2.0/node_modules/@discordjs/ws/dist/index.js:1190:51)"}
